### ISSUE TITLE
Hydro FK Constraint

### ISSUE THREAD

**Issue by jtgilbert** [Riverscapes/riverscapes-tools#1044]
e.g. HUC 0514010109

Traceback (most recent call last):
  File "/usr/local/src/riverscapes-tools/packages/hydro/hydro/hydro.py", line 304, in main
    hydro_context(args.huc, args.dem, args.hillshade, args.igo, args.dgo, args.flowlines, args.output_folder, meta)
  File "/usr/local/src/riverscapes-tools/packages/hydro/hydro/hydro.py", line 171, in hydro_context
    database.curs.execute("""INSERT INTO DGOAttributes (DGOID, FCode, level_path, seg_distance, centerline_length, segment_area)
sqlite3.IntegrityError: FOREIGN KEY constraint failed

**Comment by jtgilbert** [comment]
new example HUC 1606000212
