### ISSUE TITLE
Hydro none type error 

### ISSUE THREAD

**Issue by jtgilbert** [Riverscapes/riverscapes-tools#1047]
e.g. HUC 0430010810

Traceback (most recent call last):
  File "/usr/local/src/riverscapes-tools/packages/hydro/hydro/hydro.py", line 304, in main
    hydro_context(args.huc, args.dem, args.hillshade, args.igo, args.dgo, args.flowlines, args.output_folder, meta)
  File "/usr/local/src/riverscapes-tools/packages/hydro/hydro/hydro.py", line 151, in hydro_context
    VALUES ("{huc}", "{row['Name']}", "{row['States']}", "{row['QLow']}", "{row['Q2']}", "{row['MaxDrainage']}", "{row['EcoregionID']}")""")
TypeError: 'NoneType' object is not subscriptable

**Comment by jtgilbert** [comment]
These appear to be border HUCs for which there's not an entry in the 'Watersheds' table.
