### ISSUE TITLE
Klamath Tool Runs

### ISSUE THREAD

**Issue by philipbaileynar** [Riverscapes/riverscapes-tools#138]
Please run the latest versions of the following tools on the three HUCs for the Klamath (18010201, 18010202, 18010203). This task is complete when all the models are in the "PUBLIC_DATA" program within the riverscapes warehouse. Note there are some previous runs of RSC and VBET in there already, but these should be re-run (so that we get the segmented network).

|Tool|18010201|18010202|18010203|
|---|---|---|---|
|Riverscapes Context|Done|Done|Done|
|VBET|Done|Done|Done|
|BRAT|Not Done|Not Done|Not Done|
|RVD|Done|Done|Done|
|Confinement|Done|Done|Done|

Notes:

1. I know confinement is wrong (incorrect bankfull buffer), but let's get it run anyway and then meet with USU to discuss.
2. Please also run floodplain connectivity. My preference is that this becomes a feature within VBET (although I am starting to question this given the growing complexity of VBET related to our other discussions).

**Comment by MattReimer** [comment]
Some notes:

Cybercastor Python tools use a menu library called inquirer that can only be used in Linux.

For now let's just run these on Kelly's machine and upload using RSCli. I've got some ideas how we can get cybercastor working (I'm thinking of a remote VSCode instance on Ubuntu EC2) but until then yeah, manual.

To upload these to the warehouse:

```
rscli upload . --tags "Something"
OR
rscli upload c:\path\to\folder\where\projectxml\lives\ --tags "Something"
```

@philipbaileynar what tags should we use here? We can also use no tags if that's helpful

use `rscli upload --help` to get the POSIX help if you need more options.

**Comment by philipbaileynar** [comment]
Let's tag them with "Klamath" and "RCAT"

**Comment by KellyMWhitehead** [comment]
All projects uploaded to warehouse with tag "Klamath" except for BRAT  due to following error when running 'build brat' tool:

[error] [BRAT Build] Input shapes do not overlap raster.
Traceback (most recent call last):
  File "d:\NAR\riverscapes-tools\.venv\lib\site-packages\rasterio\mask.py", line 83, in raster_geometry_mask
    window = geometry_window(dataset, shapes, north_up=north_up, rotated=rotated,
  File "d:\NAR\riverscapes-tools\.venv\lib\site-packages\rasterio\features.py", line 469, in geometry_window
    window = window.intersection(raster_window)
  File "d:\NAR\riverscapes-tools\.venv\lib\site-packages\rasterio\windows.py", line 724, in intersection
    return intersection([self, other])
  File "d:\NAR\riverscapes-tools\.venv\lib\site-packages\rasterio\windows.py", line 119, in wrapper
    return function(*args[0])
  File "d:\NAR\riverscapes-tools\.venv\lib\site-packages\rasterio\windows.py", line 217, in intersection
    raise WindowError("windows do not intersect")
rasterio.errors.WindowError: windows do not intersect

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\NAR\riverscapes-tools\packages\brat\sqlbrat\brat_build.py", line 286, in main
    brat_build(
  File "D:\NAR\riverscapes-tools\packages\brat\sqlbrat\brat_build.py", line 179, in brat_build
    reach_geometry(reach_geometry_path, dem_raster_path, elevation_buffer)
  File "D:\NAR\riverscapes-tools\packages\brat\sqlbrat\utils\reach_geometry.py", line 68, in reach_geometry
    line_start_elevations = raster_buffer_stats2(line_start_polygons, dem_path)
  File "d:\nar\riverscapes-tools\lib\commons\rscommons\raster_buffer_stats.py", line 137, in raster_buffer_stats2
    raw_raster, _out_transform = mask(src, [polygon], crop=True)
  File "d:\NAR\riverscapes-tools\.venv\lib\site-packages\rasterio\mask.py", line 182, in mask
    shape_mask, transform, window = raster_geometry_mask(
  File "d:\NAR\riverscapes-tools\.venv\lib\site-packages\rasterio\mask.py", line 90, in raster_geometry_mask
    raise ValueError('Input shapes do not overlap raster.')
ValueError: Input shapes do not overlap raster.

**Comment by KellyMWhitehead** [comment]
Reran brat build and got the same error. Did some sleuthing around the code and looked at the data, error may be related to a few flowlines falling outside of the DEM:
![image](https://user-images.githubusercontent.com/10746997/104534343-f52b2e00-55c8-11eb-92b4-d53987edf69d.png)

**Comment by joewheaton** [comment]
> error may be related to a few flowlines falling outside of the DEM:

@KellyMWhitehead I presume this happens only on our "lower" and "middle" HUCs where the network lines extend on to the neighboring upsream HUCs?

**Comment by MattReimer** [comment]
These are all done and in the warehouse. @philipbaileynar we can re-run RVD any time you'd like but I'm closing this ticket.
