### ISSUE TITLE
BRAT Error: Input shapes do not overlap raster

### ISSUE THREAD

**Issue by MattReimer** [Riverscapes/riverscapes-tools#150]
Seems to affect HUC 10190005

```
2021-01-15 15:46:30::         PROGRESS: 1 / 26,890  (0%)  Buffer Stats     Ellapsed: 0s
2021-01-15 15:46:48:: [error] [BRAT Build] Input shapes do not overlap raster.
2021-01-15 15:46:48:: Traceback (most recent call last):
2021-01-15 15:46:48::   File "/usr/local/venv/lib/python3.8/site-packages/rasterio/mask.py", line 83, in raster_geometry_mask
2021-01-15 15:46:48::     window = geometry_window(dataset, shapes, north_up=north_up, rotated=rotated,
2021-01-15 15:46:48::   File "/usr/local/venv/lib/python3.8/site-packages/rasterio/features.py", line 469, in geometry_window
2021-01-15 15:46:48::     window = window.intersection(raster_window)
2021-01-15 15:46:48::   File "/usr/local/venv/lib/python3.8/site-packages/rasterio/windows.py", line 724, in intersection
2021-01-15 15:46:48::     return intersection([self, other])
2021-01-15 15:46:48::   File "/usr/local/venv/lib/python3.8/site-packages/rasterio/windows.py", line 119, in wrapper
2021-01-15 15:46:48::     return function(*args[0])
2021-01-15 15:46:48::   File "/usr/local/venv/lib/python3.8/site-packages/rasterio/windows.py", line 217, in intersection
2021-01-15 15:46:48::     raise WindowError("windows do not intersect")
2021-01-15 15:46:48:: rasterio.errors.WindowError: windows do not intersect
2021-01-15 15:46:48:: During handling of the above exception, another exception occurred:
2021-01-15 15:46:48:: Traceback (most recent call last):
2021-01-15 15:46:48::   File "/usr/local/src/riverscapes-tools/packages/brat/sqlbrat/brat_build.py", line 286, in main
2021-01-15 15:46:48::     brat_build(
2021-01-15 15:46:48::   File "/usr/local/src/riverscapes-tools/packages/brat/sqlbrat/brat_build.py", line 179, in brat_build
2021-01-15 15:46:48::     reach_geometry(reach_geometry_path, dem_raster_path, elevation_buffer)
2021-01-15 15:46:48::   File "/usr/local/src/riverscapes-tools/packages/brat/sqlbrat/utils/reach_geometry.py", line 68, in reach_geometry
2021-01-15 15:46:48::     line_start_elevations = raster_buffer_stats2(line_start_polygons, dem_path)
2021-01-15 15:46:48::   File "/usr/local/src/riverscapes-tools/lib/commons/rscommons/raster_buffer_stats.py", line 137, in raster_buffer_stats2
2021-01-15 15:46:48::     raw_raster, _out_transform = mask(src, [polygon], crop=True)
2021-01-15 15:46:48::   File "/usr/local/venv/lib/python3.8/site-packages/rasterio/mask.py", line 182, in mask
2021-01-15 15:46:48::     shape_mask, transform, window = raster_geometry_mask(
2021-01-15 15:46:48::   File "/usr/local/venv/lib/python3.8/site-packages/rasterio/mask.py", line 90, in raster_geometry_mask
2021-01-15 15:46:48::     raise ValueError('Input shapes do not overlap raster.')
2021-01-15 15:46:48:: ValueError: Input shapes do not overlap raster.
```

**Comment by MattReimer** [comment]
```
2021-01-18 19:30:21:: [error] [BRAT Build] CHECK constraint failed: CHK_Reaches_LengthKm
2021-01-18 19:30:21:: Traceback (most recent call last):
2021-01-18 19:30:21::   File "/usr/local/src/riverscapes-tools/packages/brat/sqlbrat/brat_build.py", line 286, in main
2021-01-18 19:30:21::     brat_build(
2021-01-18 19:30:21::   File "/usr/local/src/riverscapes-tools/packages/brat/sqlbrat/brat_build.py", line 179, in brat_build
2021-01-18 19:30:21::     reach_geometry(reach_geometry_path, dem_raster_path, elevation_buffer)
2021-01-18 19:30:21::   File "/usr/local/src/riverscapes-tools/packages/brat/sqlbrat/utils/reach_geometry.py", line 92, in reach_geometry
2021-01-18 19:30:21::     write_db_attributes(os.path.dirname(flow_lines), reaches, ['iGeo_Len', 'iGeo_ElMax', 'iGeo_ElMin', 'iGeo_Slope'])
2021-01-18 19:30:21::   File "/usr/local/src/riverscapes-tools/lib/commons/rscommons/database.py", line 244, in write_db_attributes
2021-01-18 19:30:21::     curs.executemany(sql, results)
2021-01-18 19:30:21:: sqlite3.IntegrityError: CHECK constraint failed: CHK_Reaches_LengthKm
2021-01-18 19:30:21:: <<BRAT PROCESS ENDED WITH AN ERROR>>
```

**Comment by philipbaileynar** [comment]
Note the check constraint in question (chk_reaches_lengthkm) requires the length to be greater than zero. 

https://github.com/Riverscapes/riverscapes-tools/blob/dev/packages/brat/database/brat_schema.sql#L17

If one or both ends of the reach are off the DEM they could still have a length, but it must not be zero.

**Comment by KellyMWhitehead** [comment]
Fixed by not excluding features with zero length. de066c96767859706a37badc029cd25a01d0f2f7
