### ISSUE TITLE
Vegetation raster shapes are not equal Error for huc 10190002

### ISSUE THREAD

**Issue by MattReimer** [Riverscapes/riverscapes-tools#154]
Another error for RVD:

This is related to #156 and happens because existing and historic vegetation rasters are 1 pixel different in size. 

If we require them to be the same size we can just fix #156 and close this issue. Otherwise we need a strategy for dealing with different raster shapes. 

```
2021-01-18 20:28:38:: Finished: 91,663    Clipping Polygons...     
2021-01-18 20:28:38:: [debug] [DatasetRegistry] Dataset opened: /usr/local/data/rvd/10190002/rvd/intermediates/intermediates.gpkg for WRITING
2021-01-18 20:28:38:: [debug] [VectorBase] No layer named "Thiessen" found
2021-01-18 20:28:38::         PROGRESS: 0 / 91,663  (0%)  Saving /usr/local/data/rvd/10190002/rvd/intermediates/intermediates.gpkg/Thiessen     Ellapsed: 0s
2021-01-18 20:28:42:: Finished: 91,663    Saving /usr/local/data/rvd/10190002/rvd/intermediates/intermediates.gpkg/Thiessen     
2021-01-18 20:28:42:: [debug] [DatasetRegistry] Dataset closed: /usr/local/data/rvd/10190002/rvd/intermediates/intermediates.gpkg
2021-01-18 20:28:42:: [debug] [DatasetRegistry] Dataset opened: /usr/local/data/rvd/10190002/rvd/intermediates/intermediates.gpkg for WRITING
2021-01-18 20:28:42:: [debug] [VectorBase] No layer named "ThiessenPolygonsDissolved" found
2021-01-18 20:28:42::         PROGRESS: 0 / 91,663  (0%)  Saving /usr/local/data/rvd/10190002/rvd/intermediates/intermediates.gpkg/ThiessenPolygonsDissolved     Ellapsed: 0s
2021-01-18 20:28:47:: Finished: 91,663    Saving /usr/local/data/rvd/10190002/rvd/intermediates/intermediates.gpkg/ThiessenPolygonsDissolved     
2021-01-18 20:28:48:: [debug] [DatasetRegistry] Dataset closed: /usr/local/data/rvd/10190002/rvd/intermediates/intermediates.gpkg
2021-01-18 20:28:48:: [debug] [DatasetRegistry] Dataset opened: /usr/local/data/rvd/10190002/rvd/intermediates/intermediates.gpkg for WRITING
2021-01-18 20:28:48:: [debug] [VectorBase] No layer named "ThiessenPolygonsRaw" found
2021-01-18 20:28:48::         PROGRESS: 0 / 455,773  (0%)  Saving /usr/local/data/rvd/10190002/rvd/intermediates/intermediates.gpkg/ThiessenPolygonsRaw     Ellapsed: 0s
2021-01-18 20:29:08::         PROGRESS: 336,754 / 455,773  (73%)  Saving /usr/local/data/rvd/10190002/rvd/intermediates/intermediates.gpkg/ThiessenPolygonsRaw     Ellapsed: 20s
2021-01-18 20:29:15:: Finished: 455,773    Saving /usr/local/data/rvd/10190002/rvd/intermediates/intermediates.gpkg/ThiessenPolygonsRaw     
2021-01-18 20:29:29:: [debug] [DatasetRegistry] Dataset closed: /usr/local/data/rvd/10190002/rvd/intermediates/intermediates.gpkg
2021-01-18 20:29:29:: [info] [RVD] Loading Existing and Historic Vegetation Rasters
2021-01-18 20:29:29:: [info] [MakeDir] Folder not found. Creating: /usr/local/data/rvd/10190002/rvd/Intermediates
2021-01-18 20:29:29:: [error] [RVD] Vegetation raster shapes are not equal Existing=(2504, 3047) Historic=(2505, 3047). Cannot continue
2021-01-18 20:29:29:: Traceback (most recent call last):
2021-01-18 20:29:29::   File "/usr/local/src/riverscapes-tools/packages/rvd/rvd/rvd.py", line 560, in main
2021-01-18 20:29:29::     rvd(args.huc,
2021-01-18 20:29:29::   File "/usr/local/src/riverscapes-tools/packages/rvd/rvd/rvd.py", line 227, in rvd
2021-01-18 20:29:29::     raise Exception('Vegetation raster shapes are not equal Existing={} Historic={}. Cannot continue'.format(vegetation["EXISTING"]["RAW"].shape, vegetation["HISTORIC"]["RAW"].shape))
2021-01-18 20:29:29:: Exception: Vegetation raster shapes are not equal Existing=(2504, 3047) Historic=(2505, 3047). Cannot continue
```

**Comment by MattReimer** [comment]
This is verified fixed in RSContext. Raster sizes should always match now
