### ISSUE TITLE
RVD Unique Constraint Failure

### ISSUE THREAD

**Issue by MattReimer** [Riverscapes/riverscapes-tools#163]
Relating to HUC 17060304 for RVD and 10190010 for BRAT

This is a side-effect of elated to fix for #158. These are basically the same issue in two different files.

After enabling `PRAGMA foreign_keys = ON` 

The query for `INSERT INTO ReachVegetation ...` fails

## RVD  `riverscapes-tools/packages/rvd/rvd/rvd.py`

```
2021-01-20 03:24:50:: [info] [VectorBase] Creating output field "HISTORIC_NATIVE_RIPARIAN_MEAN" in layer.
2021-01-20 03:24:50:: [info] [VectorBase] Creating output field "NATIVE_RIPARIAN_DEPARTURE" in layer.
2021-01-20 03:24:50::         PROGRESS: 1 / 3,563  (0%)  Writing Attributes     Ellapsed: 0s
2021-01-20 03:24:50:: Finished: 3,563    Writing Attributes     
2021-01-20 03:24:50:: [debug] [DatasetRegistry] Dataset closed: /usr/local/data/rvd/17060304/rvd/outputs/RVD.gpkg
2021-01-20 03:24:50:: [error] [RVD] UNIQUE constraint failed: ReachVegetation.ReachID, ReachVegetation.VegetationID
2021-01-20 03:24:50:: Traceback (most recent call last):
2021-01-20 03:24:50::   File "/usr/local/src/riverscapes-tools/packages/rvd/rvd/rvd.py", line 560, in main
2021-01-20 03:24:50::     rvd(args.huc,
2021-01-20 03:24:50::   File "/usr/local/src/riverscapes-tools/packages/rvd/rvd/rvd.py", line 382, in rvd
2021-01-20 03:24:50::     cursor.executemany('''INSERT INTO ReachVegetation (
2021-01-20 03:24:50:: sqlite3.IntegrityError: UNIQUE constraint failed: ReachVegetation.ReachID, ReachVegetation.VegetationID
2021-01-20 03:24:50:: <<RVD PROCESS ENDED WITH AN ERROR>>

```

## BRAT `riverscapes-tools/packages/brat/sqlbrat/utils/vegetation_summary.py`

```
2021-01-20 04:58:55:: [debug] [DatasetRegistry] Dataset closed: /usr/local/data/brat/10190010/brat/outputs/brat.gpkg
2021-01-20 04:58:55:: [error] [BRAT Build] FOREIGN KEY constraint failed
2021-01-20 04:58:55:: Traceback (most recent call last):
2021-01-20 04:58:55::   File "/usr/local/src/riverscapes-tools/packages/brat/sqlbrat/brat_build.py", line 286, in main
2021-01-20 04:58:55::     brat_build(
2021-01-20 04:58:55::   File "/usr/local/src/riverscapes-tools/packages/brat/sqlbrat/brat_build.py", line 189, in brat_build
2021-01-20 04:58:55::     vegetation_summary(outputs_gpkg_path, '{} {}m'.format(label, buffer), veg_raster, buffer)
2021-01-20 04:58:55::   File "/usr/local/src/riverscapes-tools/packages/brat/sqlbrat/utils/vegetation_summary.py", line 74, in vegetation_summary
2021-01-20 04:58:55::     database.conn.executemany('INSERT INTO ReachVegetation (ReachID, VegetationID, Buffer, Area, CellCount) VALUES (?, ?, ?, ?, ?)', veg_counts)
2021-01-20 04:58:55:: sqlite3.IntegrityError: FOREIGN KEY constraint failed
2021-01-20 04:58:56:: <<BRAT PROCESS ENDED WITH AN ERROR>>
```

**Comment by MattReimer** [comment]
BRAT Has been enhanced to include better errors
```
[info] [VectorBase] 1.0m distance converts to 0.0000093634 using UTM EPSG 26913
        - 'VirtualXPath'        [XML Path Language - XPath]
[debug] [DatasetRegistry] Dataset opened: /Users/matt/Work/data/bratDockerShare/brat/10190010/outputs/brat.gpkg for READING
[debug] [VectorBase] Input spatial reference is "+proj=longlat +datum=WGS84 +no_defs"  Axis Strategy: "OAMS_TRADITIONAL_GIS_ORDER"
[debug] [VectorBase] Output spatial reference is "+proj=longlat +datum=WGS84 +no_defs"  Axis Strategy: "OAMS_AUTHORITY_COMPLIANT"
[debug] [VectorBase] Input spatial reference is "+proj=longlat +datum=WGS84 +no_defs"  Axis Strategy: "OAMS_TRADITIONAL_GIS_ORDER"
[debug] [VectorBase] Output spatial reference is "+proj=longlat +datum=WGS84 +no_defs"  Axis Strategy: "OAMS_TRADITIONAL_GIS_ORDER"
Finished: 10,235    Historical Veg 30.0m     
[debug] [DatasetRegistry] Dataset closed: /Users/matt/Work/data/bratDockerShare/brat/10190010/outputs/brat.gpkg
[error] [Vegetation] Integrity Error when inserting records: ReachID: 104 VegetationID: 2718
[error] [Vegetation] Integrity Error when inserting records: ReachID: 727 VegetationID: 2718
[error] [Vegetation] Integrity Error when inserting records: ReachID: 1102 VegetationID: 2718
[error] [Vegetation] Integrity Error when inserting records: ReachID: 1306 VegetationID: 2718
[error] [Vegetation] Integrity Error when inserting records: ReachID: 1348 VegetationID: 2718
...
...
...
[error] [BRAT Build] Errors were found inserting records into the database. Cannot continue.
Traceback (most recent call last):
  File "/Users/matt/Work/Git/Riverscapes/riverscapes-tools/packages/brat/sqlbrat/brat_build.py", line 286, in main
    brat_build(
  File "/Users/matt/Work/Git/Riverscapes/riverscapes-tools/packages/brat/sqlbrat/brat_build.py", line 189, in brat_build
    vegetation_summary(outputs_gpkg_path, '{} {}m'.format(label, buffer), veg_raster, buffer)
  File "/Users/matt/Work/Git/Riverscapes/riverscapes-tools/packages/brat/sqlbrat/utils/vegetation_summary.py", line 92, in vegetation_summary
    raise Exception('Errors were found inserting records into the database. Cannot continue.')
Exception: Errors were found inserting records into the database. Cannot continue.
```

**Comment by MattReimer** [comment]
I made a mistake and the fix went into the wrong commit:
https://github.com/Riverscapes/riverscapes-tools/commit/9682a838e36ea6efe77148f35cebc432625a905a
