### ISSUE TITLE
[BRAT] Vegetation ID 2718 missing from Db

### ISSUE THREAD

**Issue by MattReimer** [Riverscapes/riverscapes-tools#169]
Look at hucs 10190002, 10190003

From the log file:

```
2021-01-21 22:40:02:: [error] [Vegetation] Integrity Error when inserting records: ReachID: 91793 VegetationID: 2718
2021-01-21 22:40:02:: [error] [Vegetation] Integrity Error when inserting records: ReachID: 91843 VegetationID: 2718
2021-01-21 22:40:02:: [error] [Vegetation] Integrity Error when inserting records: ReachID: 91847 VegetationID: 2718
2021-01-21 22:40:02:: [error] [Vegetation] Integrity Error when inserting records: ReachID: 91951 VegetationID: 2718
2021-01-21 22:40:02:: [error] [BRAT Build] Errors were found inserting records into the database. Cannot continue.
2021-01-21 22:40:02:: Traceback (most recent call last):
2021-01-21 22:40:02::   File "/usr/local/src/riverscapes-tools/packages/brat/sqlbrat/brat_build.py", line 286, in main
2021-01-21 22:40:02::     brat_build(
2021-01-21 22:40:02::   File "/usr/local/src/riverscapes-tools/packages/brat/sqlbrat/brat_build.py", line 189, in brat_build
2021-01-21 22:40:02::     vegetation_summary(outputs_gpkg_path, '{} {}m'.format(label, buffer), veg_raster, buffer)
2021-01-21 22:40:02::   File "/usr/local/src/riverscapes-tools/packages/brat/sqlbrat/utils/vegetation_summary.py", line 92, in vegetation_summary
2021-01-21 22:40:02::     raise Exception('Errors were found inserting records into the database. Cannot continue.')
2021-01-21 22:40:02:: Exception: Errors were found inserting records into the database. Cannot continue.
2021-01-21 22:40:02:: <<BRAT PROCESS ENDED WITH AN ERROR>>

```

**Comment by MattReimer** [comment]
I found 370 new values that needed to be added to Vegetation csv. I have added them with NULL Suitabilities

Also opened #171 so we can start getting those suitabilities sorted.
