### ISSUE TITLE
RVD Database "INSERT" error 18010202

### ISSUE THREAD

**Issue by MattReimer** [Riverscapes/riverscapes-tools#202]
```
2021-02-05 18:40:16:: HUC: 18010202
2021-02-05 18:40:16:: PROGRAM: AnabranchDEV
2021-02-05 18:40:16:: VBET_TAGS: FEB5
2021-02-05 18:40:16:: RSCONTEXT_TAGS: FEB5
2021-02-05 18:40:16:: RVD_TAGS: FEB5
2021-02-05 18:40:16:: GIT_REF_USE: rvd_db_tweaks
```

## [FAILED-18010202.log](https://github.com/Riverscapes/riverscapes-tools/files/5934913/FAILED-18010202.log)

```
2021-02-05 18:40:34:: [info] [VectorBase] Creating output field "WatershedID" in layer.
2021-02-05 18:40:34:: [info] [Database] Creating database schema at /usr/local/data/rvd/18010202/rvd/outputs/RVD.gpkg
2021-02-05 18:40:34:: [error] [RVD] near "INSERT": syntax error
2021-02-05 18:40:34:: Traceback (most recent call last):
2021-02-05 18:40:34::   File "/usr/local/src/riverscapes-tools/packages/rvd/rvd/rvd.py", line 668, in main
2021-02-05 18:40:34::     rvd(args.huc,
2021-02-05 18:40:34::   File "/usr/local/src/riverscapes-tools/packages/rvd/rvd/rvd.py", line 192, in rvd
2021-02-05 18:40:34::     watershed_name = create_database(huc, outputs_gpkg_path, metadata, cfg.OUTPUT_EPSG, os.path.join(os.path.abspath(os.path.dirname(__file__)), '..', 'database', 'rvd_schema.sql'))
2021-02-05 18:40:34::   File "/usr/local/src/riverscapes-tools/lib/commons/rscommons/database.py", line 87, in create_database
2021-02-05 18:40:34::     curs.executescript(qry)
2021-02-05 18:40:34:: sqlite3.OperationalError: near "INSERT": syntax error
2021-02-05 18:40:34:: <<RVD PROCESS ENDED WITH AN ERROR>>


```

**Comment by MattReimer** [comment]
5727a0a fixes this.
