### ISSUE TITLE
WIndows WSL Problem with pygeoprocessing

### ISSUE THREAD

**Issue by MattReimer** [Riverscapes/riverscapes-tools#218]
for some reason I couldn't get the master branch working on the machine belonging to @tyler1218hatch 

Could be a really simple version thing.

```
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/matt/.vscode-server/extensions/ms-python.python-2021.1.502429796/pythonFiles/lib/python/debugpy/__main__.py", line 45, in <module>
    cli.main()
  File "/home/matt/.vscode-server/extensions/ms-python.python-2021.1.502429796/pythonFiles/lib/python/debugpy/../debugpy/server/cli.py", line 444, in main
    run()
  File "/home/matt/.vscode-server/extensions/ms-python.python-2021.1.502429796/pythonFiles/lib/python/debugpy/../debugpy/server/cli.py", line 331, in run_module
    run_module_as_main(target_as_str, alter_argv=True)
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/matt/code/Riverscapes/riverscapes-tools-debug/packages/brat/sqlbrat/brat_build.py", line 27, in <module>
    from sqlbrat.utils.conflict_attributes import conflict_attributes
  File "/home/matt/code/Riverscapes/riverscapes-tools-debug/packages/brat/sqlbrat/utils/conflict_attributes.py", line 16, in <module>
    from pygeoprocessing import geoprocessing
  File "/home/matt/code/Riverscapes/riverscapes-tools-debug/.venv/lib/python3.8/site-packages/pygeoprocessing/__init__.py", line 9, in <module>
    from . import geoprocessing
  File "/home/matt/code/Riverscapes/riverscapes-tools-debug/.venv/lib/python3.8/site-packages/pygeoprocessing/geoprocessing.py", line 16, in <module>
    from . import geoprocessing_core
  File "src\pygeoprocessing\geoprocessing_core.pyx", line 1, in init pygeoprocessing.geoprocessing_core
ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Expected 88 from C header, got 80 from PyObject
```

**Comment by MattReimer** [comment]
I was able to reproduce this successfully on windows.
