### ISSUE TITLE
Confinement Error in Debug mode

### ISSUE THREAD

**Issue by KellyMWhitehead** [Riverscapes/riverscapes-tools#226]
Error when confinement is finished in debug mode:

```[error] [Confinement] main thread is not in main loop
Traceback (most recent call last):
  File "D:\NAR\riverscapes-tools\packages\gnat\gnat\confinement.py", line 600, in main
    retcode, max_obj = ThreadRun(confinement, memfile,
  File "d:\nar\riverscapes-tools\lib\commons\rscommons\debug.py", line 164, in ThreadRun
    memmon.write_plot(os.path.splitext(memlogfile)[0] + '.png')
  File "d:\nar\riverscapes-tools\lib\commons\rscommons\debug.py", line 119, in write_plot
    plt.clf()
  File "d:\NAR\riverscapes-tools\.venv\lib\site-packages\matplotlib\pyplot.py", line 822, in clf
    gcf().clf()
  File "d:\NAR\riverscapes-tools\.venv\lib\site-packages\matplotlib\figure.py", line 1800, in clf
    toolbar.update()
  File "d:\NAR\riverscapes-tools\.venv\lib\site-packages\matplotlib\backend_bases.py", line 3276, in update
    self.set_history_buttons()
  File "d:\NAR\riverscapes-tools\.venv\lib\site-packages\matplotlib\backends\_backend_tk.py", line 650, in set_history_buttons
    self._buttons['Back']['state'] = state_map[can_back]
  File "C:\Python38\lib\tkinter\__init__.py", line 1648, in __setitem__
    self.configure({key: value})
  File "C:\Python38\lib\tkinter\__init__.py", line 1637, in configure
    return self._configure('configure', cnf, kw)
  File "C:\Python38\lib\tkinter\__init__.py", line 1627, in _configure
    self.tk.call(_flatten((self._w, cmd)) + self._options(cnf))
RuntimeError: main thread is not in main loop```

**Comment by MattReimer** [comment]
This 2-year old issue can be re-opened if it still exists.
