### ISSUE TITLE
RSC project for 17050102

### ISSUE THREAD

**Issue by philipbaileynar** [Riverscapes/riverscapes-tools#274]
Please run the follow tool:

* riverscapes context
* HUC 17050102
* program Anabranch
* tags: none

please assign this ticket to me when complete

**Comment by MattReimer** [comment]
This failed with exception: "Exception: No DEM rasters identified on Science Base"

is it possible this is outside the coverage area?

```
2021-04-20 16:54:41:: [info] [Download] 0 Science base item(s) identified.
2021-04-20 16:54:41:: [error] [Science Base] Science Base Query: {'ancestors': '4f70aa9fe4b058caae3f8de5', 'filter1': 'tags=IMG', 'conjunction': 'tags=OR', 'filter2': "spatialQuery={'wkt': 'POLYGON ((-116.3188810895702 41.38730170155046, -115.0119079847944 41.38730170155046, -115.0119079847944 42.95533627858018, -116.3188810895702 42.95533627858018, -116.3188810895702 41.38730170155046))', 'relation': 'intersects', 'fields': 'Bounds'}"}
2021-04-20 16:54:41:: [error] [RS Context] No DEM rasters identified on Science Base
2021-04-20 16:54:41:: Traceback (most recent call last):
2021-04-20 16:54:41::   File "/usr/local/src/riverscapes-tools/packages/rscontext/rscontext/rs_context.py", line 465, in main
2021-04-20 16:54:41::     rs_context(args.huc, args.existing, args.historic, args.ownership, args.fairmarket, args.ecoregions, args.prism, args.output, args.download, scratch_dir, args.parallel, args.force, meta)
2021-04-20 16:54:41::   File "/usr/local/src/riverscapes-tools/packages/rscontext/rscontext/rs_context.py", line 242, in rs_context
2021-04-20 16:54:41::     dem_rasters, urls = download_dem(nhd[boundary], cfg.OUTPUT_EPSG, 0.01, ned_download_folder, ned_unzip_folder, force_download)
2021-04-20 16:54:41::   File "/usr/local/src/riverscapes-tools/lib/commons/rscommons/download_dem.py", line 49, in download_dem
2021-04-20 16:54:41::     urls = get_dem_urls(vector_path, buffer_dist)
2021-04-20 16:54:41::   File "/usr/local/src/riverscapes-tools/lib/commons/rscommons/science_base.py", line 164, in get_dem_urls
2021-04-20 16:54:41::     raise Exception('No DEM rasters identified on Science Base')
2021-04-20 16:54:41:: Exception: No DEM rasters identified on Science Base

```

**Comment by MattReimer** [comment]
A little more research:

Looks like the geometry checks out:
<img width="469" alt="Screenshot 2021-04-26 141303" src="https://user-images.githubusercontent.com/1063391/116151721-d04f5800-a699-11eb-8a9e-79eb14322dd2.png">


The JSON that's being passed to the query is here:

```json
{
    "ancestors": "4f70aa9fe4b058caae3f8de5",
    "filter1": "tags=IMG",
    "conjunction": "tags=OR",
    "filter2": "spatialQuery={'wkt': 'POLYGON ((-116.3188803186016 41.38730077867205, -115.011907959858 41.38730077867205, -115.011907959858 42.95533660982832, -116.3188803186016 42.95533660982832, -116.3188803186016 41.38730077867205))', 'relation': 'intersects', 'fields': 'Bounds'}"
}

```

When I make a more generic query to the webform I don't think I get back anything useful

https://www.sciencebase.gov/catalog/items?q=&max=20&filter=spatialQuery={%22wkt%22:%20%22POLYGON%20((-116.3188803186016%2041.38730077867205,%20-115.011907959858%2041.38730077867205,%20-115.011907959858%2042.95533660982832,%20-116.3188803186016%2042.95533660982832,%20-116.3188803186016%2041.38730077867205))%22,%22relation%22:%22intersects%22,%20%22fields%22:%22Extents%22}



the ned_parent is hardcoded into the python as:

```
# The ID of the science base parent item for 10m DEMs
# https://www.sciencebase.gov/catalog/item/4f70aa71e4b058caae3f8de1
ned_parent = '4f70aa9fe4b058caae3f8de5'
```
did that change?

**Comment by philipbaileynar** [comment]
Try another huc and see if they get NHD and Ned or if it's just this one huc that's affected.

**Comment by MattReimer** [comment]
https://data.riverscapes.xyz/#/Anabranch/e470c8b5-22b0-4da9-acb8-1c686cd5df1d

**Comment by philipbaileynar** [comment]
Given that ArcRAVE is in pieces for me right now, I actually used QRAVE to validate this. Worked. All data seems to be there! I appreciate the perseverance.
