### ISSUE TITLE
VBET Failed for Huc 16010202 (int argument is coming in None)

### ISSUE THREAD

**Issue by MattReimer** [Riverscapes/riverscapes-tools#338]
[FAILED-16010202.log](https://github.com/Riverscapes/riverscapes-tools/files/6793249/FAILED-16010202.log)

```
2021-07-08 23:20:32::     ▄   ███   ▄███▄     ▄▄▄▄▀   
2021-07-08 23:20:32::      █  █  █  █▀   ▀ ▀▀▀ █      
2021-07-08 23:20:32:: █     █ █ ▀ ▄ ██▄▄       █      
2021-07-08 23:20:32::  █    █ █  ▄▀ █▄   ▄▀   █       
2021-07-08 23:20:32::   █  █  ███   ▀███▀    ▀        
2021-07-08 23:20:32::    █▐                           
2021-07-08 23:20:32::    ▐                            
2021-07-08 23:20:32:: HUC: 16010202
2021-07-08 23:20:32:: PROGRAM: PUBLIC_DATA
2021-07-08 23:20:32:: RSCONTEXT_TAGS: VBET_EVIDENCE
2021-07-08 23:20:32:: VBET_TAGS: VBET_EVIDENCE

...

2021-07-08 23:20:59:: [warning] [get_geometry_unary_union] Invalid shape with FID=2 trying the Buffer0 technique...
2021-07-08 23:20:59:: [info] [Unary Unioning features] Completed 32 operations.  Total Time: 0.0 seconds     
2021-07-08 23:20:59:: [debug] [get_geometry_unary_union] finished iterating with list of size: 32
2021-07-08 23:20:59:: [debug] [get_geometry_unary_union] Starting final union of geom_list of size: 32
2021-07-08 23:20:59:: [debug] [get_geometry_unary_union] Byte Size of output object: 310.4KB Type: MultiPolygon IsValid: True Length: 4.712215088382489 Area: 0.0008840854732208067
2021-07-08 23:20:59:: [debug] [get_geometry_unary_union] Complete
2021-07-08 23:20:59:: [info] [VBET Network] Incorporating flow areas.
2021-07-08 23:20:59::         PROGRESS: 1 / 716  (0%)  Including Features     (Ellapsed: 0.0 seconds)
2021-07-08 23:21:00:: [info] [Including Features] Completed 716 operations.  Total Time: 0.0 seconds     
2021-07-08 23:21:00:: [info] [VBET Network] VBET network generated with 916 features
2021-07-08 23:21:00:: [info] [VBET] Building drainage area zones
2021-07-08 23:21:00:: [debug] [VectorBase] No layer named "transform_zones" found
2021-07-08 23:21:00:: [info] [VectorBase] Creating output field "StreamOrde" in layer.
2021-07-08 23:21:00:: [info] [VectorBase] Creating output field "Slope_Zone" in layer.
2021-07-08 23:21:00:: [info] [VectorBase] Creating output field "HAND_Zone" in layer.
2021-07-08 23:21:00::         PROGRESS: 1 / 5,938  (0%)  Joining attributes     (Ellapsed: 0.0 seconds)
2021-07-08 23:21:00:: [error] [VBET] int() argument must be a string, a bytes-like object or a number, not 'NoneType'
2021-07-08 23:21:00:: Traceback (most recent call last):
2021-07-08 23:21:00::   File "/usr/local/src/riverscapes-tools/packages/vbet/vbet/vbet.py", line 567, in main
2021-07-08 23:21:00::     vbet(args.huc, args.scenario_code, inputs, args.output_dir, args.vaa_table, reach_codes, args.create_centerline, meta, hand=args.hand, skip_sanitize=False, quick_mode=True)
2021-07-08 23:21:00::   File "/usr/local/src/riverscapes-tools/packages/vbet/vbet/vbet.py", line 174, in vbet
2021-07-08 23:21:00::     create_stream_size_zones(project_inputs['CATCHMENTS'], flowlines_vaa_path, 'NHDPlusID', 'StreamOrde', vbet_run['Zones'], catchments_path)
2021-07-08 23:21:00::   File "/usr/local/src/riverscapes-tools/lib/commons/rscommons/vbet_network.py", line 96, in create_stream_size_zones
2021-07-08 23:21:00::     join_id = int(feat_source.GetField(join_field))
2021-07-08 23:21:00:: TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'


```

**Comment by joewheaton** [comment]
@MattReimer this seems like it is no longer relevant? Am I wrong?

**Comment by MattReimer** [comment]
Yeah. Vbet is so different now I'll close this since the line of code it pertains to is long gone

**Comment by joewheaton** [comment]
Now that's just cool. Will make QC reading log files that much more enjoyable. Nice one @MattReimer.
> ```
> 2021-07-08 23:20:32::     ▄   ███   ▄███▄     ▄▄▄▄▀   
> 2021-07-08 23:20:32::      █  █  █  █▀   ▀ ▀▀▀ █      
> 2021-07-08 23:20:32:: █     █ █ ▀ ▄ ██▄▄       █      
> 2021-07-08 23:20:32::  █    █ █  ▄▀ █▄   ▄▀   █       
> 2021-07-08 23:20:32::   █  █  ███   ▀███▀    ▀        
> 2021-07-08 23:20:32::    █▐                           
> 2021-07-08 23:20:32::    ▐

**Comment by MattReimer** [comment]
That's just a cybercastor log. There's no ASCII art in our project logs. Gotta keep those classy. 😜
