### ISSUE TITLE
Add GeoPackage as element name to TauDEM XSD? 

### ISSUE THREAD

**Issue by joewheaton** [Riverscapes/riverscapes-tools#379]
@KellyMWhitehead  in the latest [TauDEM Project](https://data.riverscapes.xyz/#/Anabranch/5c9a3651-7d37-4813-a3ab-86a90697bf0c), we tried [testing](https://github.com/Riverscapes/RiverscapesData/issues/20) @shelbysawyer new [Business Logic](https://github.com/Riverscapes/RiverscapesXML/pull/216) and got an error loading the ChannelArea from the GeoPackage. 

![image](https://user-images.githubusercontent.com/9723905/129495358-a57aeb40-5406-426c-9444-a8f019c85246.png)

Not sure if this is a problem on the TauDEM tool side @KellyMWhitehead or on the XSD validation type @MattReimer? @philipbaileynar thoughts?

**Comment by joewheaton** [comment]
@philipbaileynar this was breaking TauDEM, but now seems to be breaking on VBET. I can't even open the latest[ VBET project](https://data.riverscapes.xyz/#/Anabranch/e2277228-9c37-442d-8ea5-d12b5c830c6d) from https://github.com/Riverscapes/RiverscapesData/issues/21#issuecomment-902828705

Here's the error message from QRAVE:
```
2021-08-20T11:40:28     INFO    BusinessLogic downloaded: C:\Users\a00687426\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\qrave_toolbar\resources\blXML\VBET.xml
2021-08-20T11:40:28     WARNING    Extraneous file removed: C:\Users\a00687426\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\qrave_toolbar\resources\symbology\Confinement\confinement_ratio.qml
2021-08-20T11:40:28     INFO    SETTINGS SET: initialized=True of type '<class 'bool'>'
2021-08-20T11:40:28     INFO    SETTINGS SET: lastDigestSync=1629481228 of type '<class 'int'>'
2021-08-20T11:43:09     INFO    Requesting digest from: https://xml.riverscapes.xyz/index.json
2021-08-20T11:43:10     INFO    Symobology downloaded: C:\Users\a00687426\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\qrave_toolbar\resources\symbology\Confinement\Confinement_Ratio.qml
2021-08-20T11:43:10     INFO    SETTINGS SET: initialized=True of type '<class 'bool'>'
2021-08-20T11:43:10     INFO    SETTINGS SET: lastDigestSync=1629481390 of type '<class 'int'>'
2021-08-20T11:43:39     INFO    Error deriving transparency from layer: argument of type 'NoneType' is not iterable
2021-08-20T12:01:54     WARNING    Error finding project xml node with path="Geopackage/Layers/Vector[@id='vbet_channel_area']"
2021-08-20T12:01:54     WARNING    Error finding project xml node with path="Geopackage/Layers/Vector[@id='vbet_active_floodplain']"
2021-08-20T12:01:54     WARNING    Error finding project xml node with path="Geopackage/Layers/Vector[@id='vbet_inactive_floodplain']"
2021-08-20T12:01:54     WARNING    Error finding project xml node with path="Intermediates/Raster[@id='RASTERIZED_CHANNEL']"
2021-08-20T12:01:54     CRITICAL    Trace: Traceback (most recent call last):
              File "C:/Users/a00687426/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qrave_toolbar\src\classes\project.py", line 45, in load
              self._build_tree()
              File "C:/Users/a00687426/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qrave_toolbar\src\classes\project.py", line 101, in _build_tree
              self.qproject = self._recurse_tree()
              File "C:/Users/a00687426/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qrave_toolbar\src\classes\project.py", line 180, in _recurse_tree
              self._recurse_tree(child_node, new_proj_el, curr_item)
              File "C:/Users/a00687426/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qrave_toolbar\src\classes\project.py", line 180, in _recurse_tree
              self._recurse_tree(child_node, new_proj_el, curr_item)
              File "C:/Users/a00687426/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qrave_toolbar\src\classes\project.py", line 180, in _recurse_tree
              self._recurse_tree(child_node, new_proj_el, curr_item)
              File "C:/Users/a00687426/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qrave_toolbar\src\classes\project.py", line 151, in _recurse_tree
              new_proj_el = xpathone_withref(self.project, proj_el, bl_el.attrib['xpath'])
              File "C:/Users/a00687426/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qrave_toolbar\src\classes\project.py", line 240, in xpathone_withref
              found = el.xpath(xpath_str)
              File "src\lxml\etree.pyx", line 1586, in lxml.etree._Element.xpath
              File "src\lxml\xpath.pxi", line 307, in lxml.etree.XPathElementEvaluator.__call__
              File "src\lxml\xpath.pxi", line 227, in lxml.etree._XPathEvaluatorBase._handle_result
             lxml.etree.XPathEvalError: Invalid expression
             ```

See [video ](https://youtu.be/aGLVxVibd68) @philipbaileynar 
[![](http://img.youtube.com/vi/aGLVxVibd68/0.jpg)](http://www.youtube.com/watch?v=aGLVxVibd68"")

**Comment by philipbaileynar** [comment]
@joewheaton is this still a problem given the recent BL and symbology changes?

**Comment by joewheaton** [comment]
I think it's been sorted...
