### ISSUE TITLE
Taudem SlopeAveDown Failure

### ISSUE THREAD

**Issue by KellyMWhitehead** [Riverscapes/riverscapes-tools#421]
Huc 7050002

```2021-09-04 13:48:58:: [info] [TauDEM] Generating SlopeAveDown
2021-09-04 13:48:58:: [info] [Subprocess] Running command: mpiexec -n 2 slopeavedown -p /usr/local/data/taudem/07050002/output/intermediates/d8flowdir_p.tif -fel /usr/local/data/taudem/07050002/output/intermediates/pitfill.tif -slpd /usr/local/data/taudem/07050002/output/outputs/slopeavedown_slpd.tif -dn 7.985804497879581
2021-09-04 13:48:58:: [info] [Subprocess] SlopeAveDown version 5.3.8
2021-09-04 13:48:58:: [info] [Subprocess] Input file /usr/local/data/taudem/07050002/output/intermediates/pitfill.tif has geographic coordinate system.
2021-09-04 13:48:58:: [info] [Subprocess] Input file /usr/local/data/taudem/07050002/output/intermediates/d8flowdir_p.tif has geographic coordinate system.
2021-09-04 13:48:58:: [info] [Subprocess] ===================================================================================
2021-09-04 13:48:58:: [info] [Subprocess] =   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
2021-09-04 13:48:58:: [info] [Subprocess] =   PID 167 RUNNING AT ip-172-31-42-221.us-west-2.compute.internal
2021-09-04 13:48:58:: [info] [Subprocess] =   EXIT CODE: 9
2021-09-04 13:48:58:: [info] [Subprocess] =   CLEANING UP REMAINING PROCESSES
2021-09-04 13:48:58:: [info] [Subprocess] =   YOU CAN IGNORE THE BELOW CLEANUP MESSAGES
2021-09-04 13:48:58:: [info] [Subprocess] ===================================================================================
2021-09-04 13:48:58:: [info] [Subprocess] YOUR APPLICATION TERMINATED WITH THE EXIT STRING: Killed (signal 9)
2021-09-04 13:48:58:: [info] [Subprocess] This typically refers to a problem with your application.
2021-09-04 13:48:58:: [info] [Subprocess] Please see the FAQ page for debugging suggestions
2021-09-04 13:48:58:: [error] [Subprocess] This run may take on the order of 3 minutes to complete.
2021-09-04 13:48:58:: [error] [Subprocess] This estimate is very approximate. 
2021-09-04 13:48:58:: [error] [Subprocess] Run time is highly uncertain as it depends on the complexity of the input data 
2021-09-04 13:48:58:: [error] [Subprocess] and speed and memory of the computer. This estimate is based on our testing on 
2021-09-04 13:48:58:: [error] [Subprocess] a dual quad core Dell Xeon E5405 2.0GHz PC with 16GB RAM.
2021-09-04 13:48:58:: [error] [Subprocess] Process returned with code 9
2021-09-04 13:48:58:: [info] [Subprocess] Command completed in 2:7.002443075180054 minutes
2021-09-04 13:48:58:: [error] [TauDEM] TauDEM: SlopeAveDown
2021-09-04 13:48:58:: Traceback (most recent call last):
2021-09-04 13:48:58::   File "/usr/local/src/riverscapes-tools/packages/taudem/taudem/taudem.py", line 315, in main
2021-09-04 13:48:58::     taudem(args.huc, args.channel, args.dem, args.output_dir, args.mask, epsg, meta)
2021-09-04 13:48:58::   File "/usr/local/src/riverscapes-tools/packages/taudem/taudem/taudem.py", line 233, in taudem
2021-09-04 13:48:58::     raise Exception('TauDEM: SlopeAveDown')
2021-09-04 13:48:58:: Exception: TauDEM: SlopeAveDown
2021-09-04 13:48:58:: <<RS CONTEXT PROCESS ENDED WITH AN ERROR>>```

**Comment by KellyMWhitehead** [comment]
Similar to #337

**Comment by KellyMWhitehead** [comment]
[FAILED-07050002.log](https://github.com/Riverscapes/riverscapes-tools/files/7131090/FAILED-07050002.log)

**Comment by MattReimer** [comment]
Same as #337 we increased the RAM to 16Gb and it seems to fix things.
