### ISSUE TITLE
Channel Area fails on Cybercastor

### ISSUE THREAD

**Issue by KellyMWhitehead** [Riverscapes/riverscapes-tools#424]
All channel area runs are failing on cybercastor with this message: 

```2021-09-10 19:24:51:: Overall job complete
2021-09-10 19:24:52:: ----- RSCli Exiting -------
2021-09-10 19:24:53:: Traceback (most recent call last):
2021-09-10 19:24:53::   File "/usr/local/venv/bin/channel", line 11, in <module>
2021-09-10 19:24:53::     load_entry_point('channel', 'console_scripts', 'channel')()
2021-09-10 19:24:53::   File "/usr/local/venv/lib/python3.8/site-packages/pkg_resources/__init__.py", line 489, in load_entry_point
2021-09-10 19:24:53::     return get_distribution(dist).load_entry_point(group, name)
2021-09-10 19:24:53::   File "/usr/local/venv/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2852, in load_entry_point
2021-09-10 19:24:53::     return ep.load()
2021-09-10 19:24:53::   File "/usr/local/venv/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2443, in load
2021-09-10 19:24:53::     return self.resolve()
2021-09-10 19:24:53::   File "/usr/local/venv/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2449, in resolve
2021-09-10 19:24:53::     module = __import__(self.module_name, fromlist=['__name__'], level=0)
2021-09-10 19:24:53::   File "/usr/local/src/riverscapes-tools/packages/channel/channel/channel.py", line 22, in <module>
2021-09-10 19:24:53::     from rscommons.math import safe_eval
2021-09-10 19:24:53::   File "/usr/local/src/riverscapes-tools/lib/commons/rscommons/math.py", line 4, in <module>
2021-09-10 19:24:53::     from sympy.parsing.sympy_parser import parse_expr, TokenError
2021-09-10 19:24:53:: ModuleNotFoundError: No module named 'sympy'
2021-09-10 19:24:53:: <<RS CONTEXT PROCESS ENDED WITH AN ERROR>>
```

Full Log example: [FAILED-16040102.log](https://github.com/Riverscapes/riverscapes-tools/files/7145973/FAILED-16040102.log)

Our test watershed runs fine locally, so I am assuming this is a cybercastor issue.

**Comment by MattReimer** [comment]
This is fixed by rebuilding the cybercastor container with a new requirements.txt file
