### ISSUE TITLE
RS Context: Union Features IndexError

### ISSUE THREAD

**Issue by KellyMWhitehead** [Riverscapes/riverscapes-tools#437]
Error Message:
```
2021-09-17 21:29:08::         PROGRESS: 1 / 53  (1%)  Adding features to output layer     (Ellapsed: 0.0 seconds)
2021-09-17 21:29:08:: [info] [Adding features to output layer] Completed 53 operations.  Total Time: 0.0 seconds     
2021-09-17 21:29:08:: [info] [get_transform_from_epsg] Input spatial reference is +proj=longlat +datum=WGS84 +no_defs
2021-09-17 21:29:08:: [info] [get_transform_from_epsg] Output spatial reference is +proj=longlat +datum=WGS84 +no_defs
2021-09-17 21:29:08:: [info] [Unioning features] Completed 1 operations.  Total Time: 0s     
2021-09-17 21:29:08:: [error] [RS Context] 
2021-09-17 21:29:08:: Traceback (most recent call last):
2021-09-17 21:29:08::   File "/usr/local/src/riverscapes-tools/packages/rscontext/rscontext/rs_context.py", line 483, in main
2021-09-17 21:29:08::     rs_context(args.huc, args.existing, args.historic, args.ownership, args.fairmarket, args.ecoregions, args.prism, args.output, args.download, scratch_dir, args.parallel, args.force, meta)
2021-09-17 21:29:08::   File "/usr/local/src/riverscapes-tools/packages/rscontext/rscontext/rs_context.py", line 161, in rs_context
2021-09-17 21:29:08::     nhd, db_path, huc_name, nhd_url = clean_nhd_data(huc, nhd_download_folder, nhd_unzip_folder, os.path.join(output_folder, 'hydrology'), cfg.OUTPUT_EPSG, False)
2021-09-17 21:29:08::   File "/usr/local/src/riverscapes-tools/lib/commons/rscommons/clean_nhd_data.py", line 44, in clean_nhd_data
2021-09-17 21:29:08::     huc_name = layer[0].GetField('name')
2021-09-17 21:29:08::   File "/usr/local/venv/lib/python3.8/site-packages/osgeo/ogr.py", line 2760, in __getitem__
2021-09-17 21:29:08::     raise IndexError
2021-09-17 21:29:08:: IndexError
2021-09-17 21:29:08:: [debug] [safe_remove_dir] Directory removed: /usr/local/data/rs_context_scratch/09040002
2021-09-17 21:29:08:: <<PROCESS COMPLETE WITH ERROR>>
```
Huc(s): 09040002

Log(s): [FAILED-09040002.log](https://github.com/Riverscapes/riverscapes-tools/files/7188804/FAILED-09040002.log)

**Comment by MattReimer** [comment]
A year-old RSContext bug. I'm calling this stale. Re-open if you disagree.
