### ISSUE TITLE
Vbet Disk space error

### ISSUE THREAD

**Issue by KellyMWhitehead** [Riverscapes/riverscapes-tools#451]
```
2021-10-07 04:49:39:: [error] [GDALError] ERR# 3 -- Free disk space available is 1089581056 bytes, whereas 2133711164 are at least necessary. You can disable this check by defining the CHECK_DISK_FREE_SPACE configuration option to FALSE.
2021-10-07 04:49:39:: [error] [VBET] Free disk space available is 1089581056 bytes, whereas 2133711164 are at least necessary. You can disable this check by defining the CHECK_DISK_FREE_SPACE configuration option to FALSE.
2021-10-07 04:49:39:: Traceback (most recent call last):
2021-10-07 04:49:39::   File "/usr/local/src/riverscapes-tools/packages/vbet/vbet/vbet.py", line 642, in main
2021-10-07 04:49:39::     vbet(args.huc, args.scenario_code, inputs, args.vaa_table, args.output_dir, reach_codes, meta, flowline_type=args.flowline_type)
2021-10-07 04:49:39::   File "/usr/local/src/riverscapes-tools/packages/vbet/vbet/vbet.py", line 335, in vbet
2021-10-07 04:49:39::     raster_clean(tmp_raw_thresh.filepath, tmp_cleaned_thresh.filepath, buffer_pixels=1)
2021-10-07 04:49:39::   File "/usr/local/src/riverscapes-tools/packages/vbet/vbet/vbet_raster_ops.py", line 272, in raster_clean
2021-10-07 04:49:39::     proximity_raster(inv_mask.filepath, tmp_prox_in.filepath, preserve_nodata=False)
2021-10-07 04:49:39::   File "/usr/local/src/riverscapes-tools/packages/vbet/vbet/vbet_raster_ops.py", line 106, in proximity_raster
2021-10-07 04:49:39::     dst_ds = drv.Create(temp_path,
2021-10-07 04:49:39::   File "/usr/local/venv/lib/python3.8/site-packages/osgeo/gdal.py", line 1908, in Create
2021-10-07 04:49:39::     return _gdal.Driver_Create(self, *args, **kwargs)
2021-10-07 04:49:39:: RuntimeError: Free disk space available is 1089581056 bytes, whereas 2133711164 are at least necessary. You can disable this check by defining the CHECK_DISK_FREE_SPACE configuration option to FALSE.
2021-10-07 04:49:40:: <<RS CONTEXT PROCESS ENDED WITH AN ERROR>>
```

Hucs: 10040104, 10100004, 10110101
[FAILED-10040104.log](https://github.com/Riverscapes/riverscapes-tools/files/7348541/FAILED-10040104.log)
[FAILED-10100004.log](https://github.com/Riverscapes/riverscapes-tools/files/7348547/FAILED-10100004.log)
[FAILED-10110101.log](https://github.com/Riverscapes/riverscapes-tools/files/7348549/FAILED-10110101.log)

**Comment by MattReimer** [comment]
This is a tricky one. There is no way to increase disk size on fargate instances. Any chance you can clean something up to make room?

**Comment by MattReimer** [comment]
Stale issue. Closing. Re-open or file a new issue if it persists.
