### ISSUE TITLE
BRAT: local variable 'count' referenced before assignment

### ISSUE THREAD

**Issue by KellyMWhitehead** [Riverscapes/riverscapes-tools#453]
```
2021-10-14 17:09:10:: [error] [BRAT Build] local variable 'count' referenced before assignment
2021-10-14 17:09:10:: Traceback (most recent call last):
2021-10-14 17:09:10::   File "/usr/local/src/riverscapes-tools/packages/brat/sqlbrat/brat_build.py", line 310, in main
2021-10-14 17:09:10::     brat_build(
2021-10-14 17:09:10::   File "/usr/local/src/riverscapes-tools/packages/brat/sqlbrat/brat_build.py", line 191, in brat_build
2021-10-14 17:09:10::     reach_geometry(reach_geometry_path, dem_raster_path, elevation_buffer)
2021-10-14 17:09:10::   File "/usr/local/src/riverscapes-tools/packages/brat/sqlbrat/utils/reach_geometry.py", line 77, in reach_geometry
2021-10-14 17:09:10::     line_end_elevations = raster_buffer_stats2(line_end_polygons, dem_path)
2021-10-14 17:09:10::   File "/usr/local/src/riverscapes-tools/lib/commons/rscommons/raster_buffer_stats.py", line 152, in raster_buffer_stats2
2021-10-14 17:09:10::     results[reach_id] = {'Mean': mean, 'Maximum': maximum, 'Minimum': minimum, 'Count': count, 'Sum': rsum}
2021-10-14 17:09:10:: UnboundLocalError: local variable 'count' referenced before assignment
2021-10-14 17:09:10:: <<BRAT PROCESS ENDED WITH AN ERROR>>\n\n
```

Huc 17050101, 17110021

[FAILED-17050101.log](https://github.com/Riverscapes/riverscapes-tools/files/7354821/FAILED-17050101.log)
[FAILED-17110021.log](https://github.com/Riverscapes/riverscapes-tools/files/7354825/FAILED-17110021.log)

**Comment by KellyMWhitehead** [comment]
fixed in 9d885ce03a121b55767b00abdd64747c1e1d4384
