### ISSUE TITLE
BRAT: Errors were found inserting records into the database

### ISSUE THREAD

**Issue by KellyMWhitehead** [Riverscapes/riverscapes-tools#454]
There were 100 or so "Integrity Error when inserting records" log messages before the following error:
```
2021-10-14 18:39:33:: [error] [Vegetation] Integrity Error when inserting records: ReachID: 17108 VegetationID: -9999
2021-10-14 18:39:33:: [error] [Vegetation] Integrity Error when inserting records: ReachID: 17109 VegetationID: -9999
2021-10-14 18:39:33:: [error] [Vegetation] Integrity Error when inserting records: ReachID: 17110 VegetationID: -9999
2021-10-14 18:39:33:: [error] [BRAT Build] Errors were found inserting records into the database. Cannot continue.
2021-10-14 18:39:33:: Traceback (most recent call last):
2021-10-14 18:39:33::   File "/usr/local/src/riverscapes-tools/packages/brat/sqlbrat/brat_build.py", line 310, in main
2021-10-14 18:39:33::     brat_build(
2021-10-14 18:39:33::   File "/usr/local/src/riverscapes-tools/packages/brat/sqlbrat/brat_build.py", line 201, in brat_build
2021-10-14 18:39:33::     vegetation_summary(outputs_gpkg_path, '{} {}m'.format(label, buffer), veg_raster, buffer)
2021-10-14 18:39:33::   File "/usr/local/src/riverscapes-tools/packages/brat/sqlbrat/utils/vegetation_summary.py", line 92, in vegetation_summary
2021-10-14 18:39:33::     raise Exception('Errors were found inserting records into the database. Cannot continue.')
2021-10-14 18:39:33:: Exception: Errors were found inserting records into the database. Cannot continue.
2021-10-14 18:39:33:: <<BRAT PROCESS ENDED WITH AN ERROR>>\n\n
```

Hucs: 17010215,
[FAILED-17010216.log](https://github.com/Riverscapes/riverscapes-tools/files/7354810/FAILED-17010216.log)

**Comment by philipbaileynar** [comment]
This suggests the veg rasters have nodata in them. I think we should filter these values out and not store them in the geopackage. I wonder if doing so will skew the veg statistics? Might be worth eyeballing where these -9999 values occur in the veg rasters.
