### ISSUE TITLE
Install Error for 0.1.13 on QGIS 3.20.2

### ISSUE THREAD

**Issue by joewheaton** [Riverscapes/riverscapes-tools#718]
I tried installing QRiS 0.1.13 and got this error:
```
Couldn't load plugin 'qris_deploy' due to an error when calling its classFactory() method 

ImportError: cannot import name 'QgsAttributeEditorAction' from 'qgis.core' (C:\PROGRA~1/QGIS32~1.2/apps/qgis/./python\qgis\core\__init__.py) 
Traceback (most recent call last):
  File "C:\PROGRA~1/QGIS32~1.2/apps/qgis/./python\qgis\utils.py", line 335, in _startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "C:\Users/a00687426/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qris_deploy\__init__.py", line 40, in classFactory
    from .src.qris_toolbar import QRiSToolbar
  File "C:\PROGRA~1/QGIS32~1.2/apps/qgis/./python\qgis\utils.py", line 799, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:\Users/a00687426/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qris_deploy\src\qris_toolbar.py", line 40, in 
    from .view.frm_dockwidget import QRiSDockWidget
  File "C:\PROGRA~1/QGIS32~1.2/apps/qgis/./python\qgis\utils.py", line 799, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:\Users/a00687426/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qris_deploy\src\view\frm_dockwidget.py", line 58, in 
    from .frm_slider import FrmSlider
  File "C:\PROGRA~1/QGIS32~1.2/apps/qgis/./python\qgis\utils.py", line 799, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:\Users/a00687426/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qris_deploy\src\view\frm_slider.py", line 14, in 
    from ..QRiS.qris_map_manager import QRisMapManager
  File "C:\PROGRA~1/QGIS32~1.2/apps/qgis/./python\qgis\utils.py", line 799, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:\Users/a00687426/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qris_deploy\src\QRiS\qris_map_manager.py", line 4, in 
    from .riverscapes_map_manager import RiverscapesMapManager
  File "C:\PROGRA~1/QGIS32~1.2/apps/qgis/./python\qgis\utils.py", line 799, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:\Users/a00687426/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qris_deploy\src\QRiS\riverscapes_map_manager.py", line 13, in 
    from qgis.core import (
ImportError: cannot import name 'QgsAttributeEditorAction' from 'qgis.core' (C:\PROGRA~1/QGIS32~1.2/apps/qgis/./python\qgis\core\__init__.py)


Python version: 3.9.5 (tags/v3.9.5:0a7dcbd, May  3 2021, 17:27:52) [MSC v.1928 64 bit (AMD64)] 
QGIS version: 3.20.2-Odense Odense, 9f59a156 

Python Path:
C:\Users/a00687426/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\spatial_query_with_values
C:/PROGRA~1/QGIS32~1.2/apps/qgis/./python
C:/Users/a00687426/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:/Users/a00687426/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins
C:/PROGRA~1/QGIS32~1.2/apps/qgis/./python/plugins
C:\Program Files\QGIS 3.20.2\bin\python39.zip
C:\PROGRA~1\QGIS32~1.2\apps\Python39\DLLs
C:\PROGRA~1\QGIS32~1.2\apps\Python39\lib
C:\Program Files\QGIS 3.20.2\bin
C:\PROGRA~1\QGIS32~1.2\apps\Python39
C:\PROGRA~1\QGIS32~1.2\apps\Python39\lib\site-packages
C:\PROGRA~1\QGIS32~1.2\apps\Python39\lib\site-packages\win32
C:\PROGRA~1\QGIS32~1.2\apps\Python39\lib\site-packages\win32\lib
C:\PROGRA~1\QGIS32~1.2\apps\Python39\lib\site-packages\Pythonwin
C:/Users/a00687426/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:\Users\a00687426\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\DigitizingTools\tools
C:\Users\a00687426\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\DigitizingTools
```

**Comment by joewheaton** [comment]
The installation above was on my old desktop with QGIS 3.20.1. I tried on my laptop with QGIS 3.28.3 and installed successfully. Do we have a depencies that is post 3.20? I will attempt upgrading now on old desktop to troubleshoot.
