### ISSUE TITLE
RSContext Bug

### ISSUE THREAD

**Issue by MattReimer** [Riverscapes/riverscapes-tools#723]
Hey @jtgilbert I need RSContext to be able to go through in order to test the new Cybercastor. Seems like it's failing on some self-intersecting problems in `nhdArea`. Is there some strategy to get through this? Can we just throw an error in the loop and continue?

This is for HUC `17060304` running RSContext on the `rscontext_update` branch

- I am using the latest NationalProject

From the logs:

```
[info] [Split NHD Area] Splitting NHD Area by NHD Plus Catchments and attributing features with NHDPlusID
[error] [GDALError] ERR# 1 -- TopologyException: Input geom 0 is invalid: Ring Self-intersection at or near point -115.90410977889135 46.149805983299522 at -115.90410977889135 46.149805983299522
[error] [RS Context] TopologyException: Input geom 0 is invalid: Ring Self-intersection at or near point -115.90410977889135 46.149805983299522 at -115.90410977889135 46.149805983299522
Traceback (most recent call last):
  File "/usr/local/src/riverscapes-tools/packages/rscontext/rscontext/rs_context.py", line 547, in main
    rs_context(args.huc, args.landfire_dir, args.ownership, args.fairmarket, args.ecoregions, args.states, args.counties, args.geology, args.prism, args.output, args.download, scratch_dir, args.parallel, args.force, meta)
  File "/usr/local/src/riverscapes-tools/packages/rscontext/rscontext/rs_context.py", line 204, in rs_context
    nhdarea_split = split_nhd_area(nhd['NHDArea'], nhd['NHDPlusCatchment'], os.path.join(nhd_unzip_folder, 'NHDAreaSplit.shp'))
  File "/usr/local/src/riverscapes-tools/packages/rscontext/rscontext/nhdarea.py", line 32, in split_nhd_area
    outids[id].append(geom.Intersection(ftr.GetGeometryRef()))
  File "/usr/lib/python3/dist-packages/osgeo/ogr.py", line 6468, in Intersection
    return _ogr.Geometry_Intersection(self, *args)
RuntimeError: TopologyException: Input geom 0 is invalid: Ring Self-intersection at or near point -115.90410977889135 46.149805983299522 at -115.90410977889135 46.149805983299522
[debug] [safe_remove_dir] Directory removed: /usr/local/data/rs_context_scratch/17060304
```

**Comment by KellyMWhitehead** [comment]
ogr geometires have a `MakeValid()` method with newer versions of GEOS. I have used it in vbet, so the version we use on cybercastor should be meeting this version level. 

https://gdal.org/doxygen/classOGRGeometry.html#a700a2d4b1c719e1f65fa3009bfc04f78

**Comment by MattReimer** [comment]
@philipbaileynar  This one's fixed. there was another one behind it though. This is a bigger discussion we need to have

**Comment by joewheaton** [comment]
> @philipbaileynar This one's fixed. there was another one behind it though. This is a bigger discussion we need to have

What is that discussion? When do you want to have it?
