### ISSUE TITLE
Python Error When Opening Newest VBET Project

### ISSUE THREAD

**Issue by shelbysawyer** [Riverscapes/riverscapes-tools#729]
I tried to open [a 0.9.0 project](https://northarrowresearchlabs.github.io/riverscapes-staging/#/Anabranch/e3999de0-2c20-48c0-8065-dc671ac1cecc) today to look for other examples of #728 but I got this error message:

```
An error has occurred while executing Python code: 

AttributeError: 'NoneType' object has no attribute 'text' 
Traceback (most recent call last):
  File "C:/Users/shelby/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qrave_toolbar\src\qrave_toolbar.py", line 355, in projectBrowserDlg
    self.dockwidget.add_project(dialog_return[0])
  File "C:/Users/shelby/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qrave_toolbar\src\dock_widget.py", line 207, in add_project
    basename = test_project.qproject.text()
AttributeError: 'NoneType' object has no attribute 'text'


Python version: 3.7.0 (v3.7.0:1bf9cc5093, Jun 27 2018, 04:59:51) [MSC v.1914 64 bit (AMD64)] 
QGIS version: 3.18.2-Zürich Zürich, 515138c171 

Python Path:
C:/PROGRA~1/QGIS3~1.18/apps/qgis/./python
C:/Users/shelby/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:/Users/shelby/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins
C:/PROGRA~1/QGIS3~1.18/apps/qgis/./python/plugins
C:\PROGRA~1\QGIS3~1.18\apps\Python37
C:\PROGRA~1\QGIS3~1.18\apps\Python37\Scripts
C:\Program Files\QGIS 3.18\bin\python37.zip
C:\PROGRA~1\QGIS3~1.18\apps\Python37\DLLs
C:\PROGRA~1\QGIS3~1.18\apps\Python37\lib
C:\Program Files\QGIS 3.18\bin
C:\PROGRA~1\QGIS3~1.18\apps\Python37\lib\site-packages
C:\PROGRA~1\QGIS3~1.18\apps\Python37\lib\site-packages\win32
C:\PROGRA~1\QGIS3~1.18\apps\Python37\lib\site-packages\win32\lib
C:\PROGRA~1\QGIS3~1.18\apps\Python37\lib\site-packages\Pythonwin
C:/Users/shelby/AppData/Roaming/QGIS/QGIS3\profiles\default/python
```

**Comment by shelbysawyer** [comment]
Hold up-- I updated resources and tried again and it seems to have opened fine. Sorry for the false alarm

**Comment by MattReimer** [comment]
I'm closing this one now. I think we've solved the issue. re-open if not.
