### ISSUE TITLE
Anthro key error

### ISSUE THREAD

**Issue by KellyMWhitehead** [Riverscapes/riverscapes-tools#778]
Several Anthro projects failed with similar errors:
```
2023-04-19 23:13:39:: [error] [Anthropogenic Context] 9140
2023-04-19 23:13:39::   all_bounds = [bounds(shape, transform=~dataset.transform) for shape in shapes]
2023-04-19 23:13:39:: Traceback (most recent call last):
2023-04-19 23:13:39:: /usr/local/lib/python3.8/dist-packages/rasterio/features.py:290: ShapelyDeprecationWarning: Iteration over multi-part geometries is deprecated and will be removed in Shapely 2.0. Use the `geoms` property to access the constituent parts of a multi-part geometry.
2023-04-19 23:13:39::   File "/usr/local/src/riverscapes-tools/packages/anthro/anthro/anthro.py", line 314, in main
2023-04-19 23:13:39::   for index, item in enumerate(shapes):
2023-04-19 23:13:39::     anthro_context(
2023-04-19 23:13:39:: /usr/local/lib/python3.8/dist-packages/rasterio/features.py:447: ShapelyDeprecationWarning: Iteration over multi-part geometries is deprecated and will be removed in Shapely 2.0. Use the `geoms` property to access the constituent parts of a multi-part geometry.
2023-04-19 23:13:39::   File "/usr/local/src/riverscapes-tools/packages/anthro/anthro/anthro.py", line 232, in anthro_context
2023-04-19 23:13:39::   all_bounds = [bounds(shape, transform=~dataset.transform) for shape in shapes]
2023-04-19 23:13:39::     lui_raster(existing_veg, outputs_gpkg_path, os.path.join(os.path.dirname(intermediates_gpkg_path), 'lui.tif'))
2023-04-19 23:13:39:: /usr/local/lib/python3.8/dist-packages/rasterio/features.py:290: ShapelyDeprecationWarning: Iteration over multi-part geometries is deprecated and will be removed in Shapely 2.0. Use the `geoms` property to access the constituent parts of a multi-part geometry.
2023-04-19 23:13:39::   File "/usr/local/src/riverscapes-tools/packages/anthro/anthro/utils/lui_raster.py", line 39, in lui_raster
2023-04-19 23:13:39::   for index, item in enumerate(shapes):
2023-04-19 23:13:39::     out_array[j, i] = int(results[veg_arr[j, i]] * 100)
2023-04-19 23:13:39:: /usr/local/lib/python3.8/dist-packages/rasterio/features.py:447: ShapelyDeprecationWarning: Iteration over multi-part geometries is deprecated and will be removed in Shapely 2.0. Use the `geoms` property to access the constituent parts of a multi-part geometry.
2023-04-19 23:13:39:: KeyError: 9140
2023-04-19 23:13:39::   all_bounds = [bounds(shape, transform=~dataset.transform) for shape in shapes]
```
hucs
- 0504000303
- 0504000303
- 0601020201
- 0502000403
- 0501000306
- 0501000301
- 0808010206

**Comment by jtgilbert** [comment]
looks like this is caused by the vegetation table being incomplete. I'm surprised it only showed up in 6 HUCs, there's a ton of missing info. Looking for a more complete version to use now.
