### ISSUE TITLE
VBET Mask/Raster Extent Issue with "None" LevelPath

### ISSUE THREAD

**Issue by KellyMWhitehead** [Riverscapes/riverscapes-tools#779]
I started looking into this, but wasn't able to get to the bottom of the issue:
```
2023-04-18 22:21:18:: [error] [VBET] Mask and data not compatible: data size is 1734, mask size is 1735.
2023-04-18 22:21:18:: Traceback (most recent call last):
2023-04-18 22:21:18::   File "/usr/local/src/riverscapes-tools/packages/vbet/vbet/vbet.py", line 1006, in main
2023-04-18 22:21:18::     vbet_centerlines(
2023-04-18 22:21:18::   File "/usr/local/src/riverscapes-tools/packages/vbet/vbet/vbet.py", line 553, in vbet_centerlines
2023-04-18 22:21:18:: /usr/local/src/riverscapes-tools/packages/vbet/vbet/vbet.py:563: RuntimeWarning: invalid value encountered in sqrt
2023-04-18 22:21:18::     transformed[name] = np.ma.MaskedArray(trans_ds, mask=block['HAND'].mask)
2023-04-18 22:21:18::   File "/usr/local/lib/python3.8/dist-packages/numpy/ma/core.py", line 2906, in __new__
2023-04-18 22:21:18::   transformed[name] = transformed[name] - (np.sqrt(masked_prox) / np.sqrt(max_prox))
2023-04-18 22:21:18::     raise MaskError(msg % (nd, nm))
2023-04-18 22:21:18:: /usr/local/src/riverscapes-tools/packages/vbet/vbet/vbet.py:563: RuntimeWarning: invalid value encountered in sqrt
2023-04-18 22:21:18:: numpy.ma.core.MaskError: Mask and data not compatible: data size is 1734, mask size is 1735.
```
This is affecting the final iteration of LevelPath (`LevelPathI is None`), all others finished just fine.

Relevant Data:
[FAILED-0801010002.log](https://github.com/Riverscapes/riverscapes-tools/files/11299766/FAILED-0801010002.log)
[Context](https://warehouse.riverscapes.net/p/56dc3d71-2ed5-4277-9758-1e78bff7e418/)
[Channel](https://warehouse.riverscapes.net/p/515b75e1-dbd6-4b06-9e89-356e6e53555c/)
[Taudem](https://warehouse.riverscapes.net/p/f3c1b504-9b5c-44c7-a22c-8506e2bca903/)

@jtgilbert if you have a chance to take a look, you might have some insight as to the issue. This huc is a chuck of mainstem Mississippi River, not sure if that is the cause of the issue, but would be good to know in case it affects other similar reaches.

**Comment by jtgilbert** [comment]
This one's got me perplexed, doesn't happen when I run it locally.

**Comment by joewheaton** [comment]
Depending on how many of these arise, maybe just run locally and manually upload. Doesn't sound like it will be that common.
