### ISSUE TITLE
RCAT Missing Key Errors

### ISSUE THREAD

**Issue by KellyMWhitehead** [Riverscapes/riverscapes-tools#801]
Key -1111 (Vegetation Raster)
```
2023-07-12 13:48:31:: [info] [Reach DGOs] Finding DGOs associated with each input reach
2023-07-12 13:48:31:: [info] [VectorBase] 100m distance converts to 0.0010309173 using UTM EPSG 26913
2023-07-12 13:48:31:: [info] [Reach DGOs] feature 276 has no associated DGOs, using 100m buffer
2023-07-12 13:48:31:: [info] [RCAT Vegetation Rasters] Generating RCAT vegetation rasters
2023-07-12 13:48:31:: [error] [RCAT] -1111
2023-07-12 13:48:31:: Traceback (most recent call last):
2023-07-12 13:48:31::   File "/usr/local/src/riverscapes-tools/packages/rcat/rcat/rcat.py", line 370, in main
2023-07-12 13:48:31::     rcat(args.huc, args.existing_veg, args.historic_veg, args.pitfilled, args.igo, args.dgo,
2023-07-12 13:48:31::   File "/usr/local/src/riverscapes-tools/packages/rcat/rcat/rcat.py", line 271, in rcat
2023-07-12 13:48:31::     rcat_rasters(prj_existing_path, prj_historic_path, outputs_gpkg_path, intermediates)
2023-07-12 13:48:31::   File "/usr/local/src/riverscapes-tools/packages/rcat/rcat/lib/veg_rasters.py", line 72, in rcat_rasters
2023-07-12 13:48:31::     hist_riparian_arr[j, i] = int(hriparian_vals[histveg_arr[j, i]])
2023-07-12 13:48:31:: KeyError: -1111
2023-07-12 13:48:31:: <<RCAT PROCESS ENDED WITH AN ERROR>>
```
[FAILED-1005001503.log](https://github.com/Riverscapes/riverscapes-tools/files/12030337/FAILED-1005001503.log)

Key 4 (moving Window)

```
2023-07-12 14:14:56:: [info] [Copy Features] Copying features from igo with specified attributes into project
2023-07-12 14:14:56::         PROGRESS: 1 / 8,885  (0%)  Processing points     (Ellapsed: 0.0 seconds)
2023-07-12 14:14:56:: [warning] [GDALError] ERR# 1 -- A geometry of type POINT is inserted into layer IGOGeometry of geometry type MULTIPOINT, which is not normally allowed by the GeoPackage specification, but the driver will however do it. To create a conformant GeoPackage, if using ogr2ogr, the -nlt option can be used to override the layer geometry type. This warning will no longer be emitted for this combination of layer and feature geometry type.
2023-07-12 14:14:56:: [info] [Processing points] Completed 8,885 operations.  Total Time: 0.0 seconds     
2023-07-12 14:14:56:: [info] [Copy Features] Copying features from reaches with specified attributes into project
2023-07-12 14:14:56::         PROGRESS: 1 / 3,942  (0%)  Processing points     (Ellapsed: 0.0 seconds)
2023-07-12 14:14:57:: [warning] [GDALError] ERR# 1 -- A geometry of type LINESTRING is inserted into layer ReachGeometry of geometry type MULTILINESTRING, which is not normally allowed by the GeoPackage specification, but the driver will however do it. To create a conformant GeoPackage, if using ogr2ogr, the -nlt option can be used to override the layer geometry type. This warning will no longer be emitted for this combination of layer and feature geometry type.
2023-07-12 14:14:57:: [info] [Processing points] Completed 3,942 operations.  Total Time: 0.0 seconds     
2023-07-12 14:14:57::         PROGRESS: 1 / 11  (9%)  Finding windows on 40000200001494.0     (Ellapsed: 0.0 seconds)
2023-07-12 14:14:57:: [error] [RCAT] '4'
2023-07-12 14:14:57:: Traceback (most recent call last):
2023-07-12 14:14:57::   File "/usr/local/src/riverscapes-tools/packages/rcat/rcat/rcat.py", line 370, in main
2023-07-12 14:14:57::     rcat(args.huc, args.existing_veg, args.historic_veg, args.pitfilled, args.igo, args.dgo,
2023-07-12 14:14:57::   File "/usr/local/src/riverscapes-tools/packages/rcat/rcat/rcat.py", line 210, in rcat
2023-07-12 14:14:57::     windows = get_moving_windows(igo_geom_path, input_layers['ANTHRODGO'], levelpathsin, distance_in)
2023-07-12 14:14:57::   File "/usr/local/src/riverscapes-tools/lib/commons/rscommons/moving_window.py", line 17, in get_moving_windows
2023-07-12 14:14:57::     window_distance = distance[str(feat_seg_pt.GetField('stream_size'))]
2023-07-12 14:14:57:: KeyError: '4'
2023-07-12 14:14:57:: <<RCAT PROCESS ENDED WITH AN ERROR>>
```

[FAILED-1501000206.log](https://github.com/Riverscapes/riverscapes-tools/files/12030363/FAILED-1501000206.log)

Key 3 (moving Window)

```
2023-07-12 17:16:47:: [info] [Copy Features] Copying features from igo with specified attributes into project
2023-07-12 17:16:47::         PROGRESS: 1 / 5,876  (0%)  Processing points     (Ellapsed: 0.0 seconds)
2023-07-12 17:16:48:: [warning] [GDALError] ERR# 1 -- A geometry of type POINT is inserted into layer IGOGeometry of geometry type MULTIPOINT, which is not normally allowed by the GeoPackage specification, but the driver will however do it. To create a conformant GeoPackage, if using ogr2ogr, the -nlt option can be used to override the layer geometry type. This warning will no longer be emitted for this combination of layer and feature geometry type.
2023-07-12 17:16:48:: [info] [Processing points] Completed 5,876 operations.  Total Time: 0.0 seconds     
2023-07-12 17:16:48:: [info] [Copy Features] Copying features from reaches with specified attributes into project
2023-07-12 17:16:48::         PROGRESS: 1 / 3,063  (0%)  Processing points     (Ellapsed: 0.0 seconds)
2023-07-12 17:16:48:: [warning] [GDALError] ERR# 1 -- A geometry of type LINESTRING is inserted into layer ReachGeometry of geometry type MULTILINESTRING, which is not normally allowed by the GeoPackage specification, but the driver will however do it. To create a conformant GeoPackage, if using ogr2ogr, the -nlt option can be used to override the layer geometry type. This warning will no longer be emitted for this combination of layer and feature geometry type.
2023-07-12 17:16:48:: [info] [Processing points] Completed 3,063 operations.  Total Time: 0.0 seconds     
2023-07-12 17:16:48::         PROGRESS: 1 / 38  (2%)  Finding windows on 55000500182580.0     (Ellapsed: 0.0 seconds)
2023-07-12 17:16:48:: [error] [RCAT] '3'
2023-07-12 17:16:48:: Traceback (most recent call last):
2023-07-12 17:16:48::   File "/usr/local/src/riverscapes-tools/packages/rcat/rcat/rcat.py", line 370, in main
2023-07-12 17:16:48::     rcat(args.huc, args.existing_veg, args.historic_veg, args.pitfilled, args.igo, args.dgo,
2023-07-12 17:16:48::   File "/usr/local/src/riverscapes-tools/packages/rcat/rcat/rcat.py", line 210, in rcat
2023-07-12 17:16:48::     windows = get_moving_windows(igo_geom_path, input_layers['ANTHRODGO'], levelpathsin, distance_in)
2023-07-12 17:16:48::   File "/usr/local/src/riverscapes-tools/lib/commons/rscommons/moving_window.py", line 17, in get_moving_windows
2023-07-12 17:16:48::     window_distance = distance[str(feat_seg_pt.GetField('stream_size'))]
2023-07-12 17:16:48:: KeyError: '3'
2023-07-12 17:16:48:: <<RCAT PROCESS ENDED WITH AN ERROR>>
```
[FAILED-1705010106.log](https://github.com/Riverscapes/riverscapes-tools/files/12030691/FAILED-1705010106.log)

**Comment by jtgilbert** [comment]
Thanks @KellyMWhitehead two of these are same bug from Anthro I missed in rcat

**Comment by KellyMWhitehead** [comment]
@jtgilbert I think this is also impacting sqlBrat:

```
2023-07-17 18:31:27:: [error] [Vegetation] Integrity Error when inserting records: ReachID: 2650 VegetationID: -1111
2023-07-17 18:31:27:: [error] [Vegetation] Integrity Error when inserting records: ReachID: 2651 VegetationID: -1111
2023-07-17 18:31:27:: [error] [Vegetation] Integrity Error when inserting records: ReachID: 2652 VegetationID: -1111
2023-07-17 18:31:27:: [error] [BRAT Build] Errors were found inserting records into the database. Cannot continue.
2023-07-17 18:31:27:: Traceback (most recent call last):
2023-07-17 18:31:27::   File "/usr/local/src/riverscapes-tools/packages/brat/sqlbrat/brat_build.py", line 334, in main
2023-07-17 18:31:27::     brat_build(
2023-07-17 18:31:27::   File "/usr/local/src/riverscapes-tools/packages/brat/sqlbrat/brat_build.py", line 215, in brat_build
2023-07-17 18:31:27::     vegetation_summary(outputs_gpkg_path, '{} {}m'.format(label, buffer), veg_raster, buffer, polygon_path)
2023-07-17 18:31:27::   File "/usr/local/src/riverscapes-tools/packages/brat/sqlbrat/utils/vegetation_summary.py", line 97, in vegetation_summary
2023-07-17 18:31:27::     raise Exception('Errors were found inserting records into the database. Cannot continue.')
2023-07-17 18:31:27:: Exception: Errors were found inserting records into the database. Cannot continue.
2023-07-17 18:31:27:: <<BRAT PROCESS ENDED WITH AN ERROR>>\n\n
```
