### ISSUE TITLE
BRAT Report error: 'AxesSubplot' object has no attribute 'bar_label'

### ISSUE THREAD

**Issue by KellyMWhitehead** [Riverscapes/riverscapes-tools#807]
Brat runs on Production are failing with the following error:

```
2023-07-17 18:30:27:: [info] [BratReport] Summarizing dam capacity outputs
2023-07-17 18:30:27:: [error] [BRAT Run] 'AxesSubplot' object has no attribute 'bar_label'
2023-07-17 18:30:27:: Traceback (most recent call last):
2023-07-17 18:30:27::   File "/usr/local/src/riverscapes-tools/packages/brat/sqlbrat/brat_run.py", line 263, in main
2023-07-17 18:30:27::     brat_run(args.project, args.csv_dir)
2023-07-17 18:30:27::   File "/usr/local/src/riverscapes-tools/packages/brat/sqlbrat/brat_run.py", line 147, in brat_run
2023-07-17 18:30:27::     report = BratReport(gpkg_path, report_path, project)
2023-07-17 18:30:27::   File "/usr/local/src/riverscapes-tools/packages/brat/sqlbrat/brat_report.py", line 157, in __init__
2023-07-17 18:30:27::     self.dam_capacity(outputs_section)
2023-07-17 18:30:27::   File "/usr/local/src/riverscapes-tools/packages/brat/sqlbrat/brat_report.py", line 220, in dam_capacity
2023-07-17 18:30:27::     self.attribute_table_and_pie('oCC_EX', [
2023-07-17 18:30:27::   File "/usr/local/src/riverscapes-tools/packages/brat/sqlbrat/brat_report.py", line 700, in attribute_table_and_pie
2023-07-17 18:30:27::     horizontal_bar([x[2] for x in data], [x[0] for x in data], col, 'Reach Length (km)', '{} by Stream Length'.format(self.f_names[attribute_field]), bar_path, 'Reach Length (Miles)')
2023-07-17 18:30:27::   File "/usr/local/src/riverscapes-tools/lib/commons/rscommons/plotting.py", line 130, in horizontal_bar
2023-07-17 18:30:27::     ax.bar_label(hbars, labels=['%.0f %%' % i for i in bar_labels], padding=5)
2023-07-17 18:30:27:: AttributeError: 'AxesSubplot' object has no attribute 'bar_label'
2023-07-17 18:30:28:: <<BRAT PROCESS ENDED WITH AN ERROR>>\n\n
```

Ran this site successfully on Windows (WSL). This doesn't seem to affect staging either.

[FAILED-1701010107.log](https://github.com/Riverscapes/riverscapes-tools/files/12073481/FAILED-1701010107.log)

**Comment by MattReimer** [comment]
I have upgraded pygeoprocessing and matplotlib in the requirements.txt file 

See:

- e320681f16ccd2f9a6abeed02d09272ced8dde11
- b2568af73353b57f20c977a4858f21eb6f3dc220

Try it again and close the issue if it's fixed.
