### ISSUE TITLE
BRAT intersection error

### ISSUE THREAD

**Issue by KellyMWhitehead** [Riverscapes/riverscapes-tools#816]
```
2023-07-27 17:34:51:: [debug] [intersect_geometry_with_feature_class] Finding intersections (may take a few minutes)...
2023-07-27 17:34:51:: [error] [BRAT Build] 'NoneType' object has no attribute 'intersection'
2023-07-27 17:34:51:: Traceback (most recent call last):
2023-07-27 17:34:51::   File "/usr/local/src/riverscapes-tools/packages/brat/sqlbrat/brat_build.py", line 334, in main
2023-07-27 17:34:51::     brat_build(
2023-07-27 17:34:51::   File "/usr/local/src/riverscapes-tools/packages/brat/sqlbrat/brat_build.py", line 205, in brat_build
2023-07-27 17:34:51::     conflict_attributes(outputs_gpkg_path, reach_geometry_path,
2023-07-27 17:34:51::   File "/usr/local/src/riverscapes-tools/packages/brat/sqlbrat/utils/conflict_attributes.py", line 55, in conflict_attributes
2023-07-27 17:34:51::     values = calc_conflict_attributes(flowlines_path, valley_bottom, roads, rail, canals, ownership, buffer_distance_metres, cell_size_meters, epsg, canal_codes, intermediates_gpkg_path)
2023-07-27 17:34:51::   File "/usr/local/src/riverscapes-tools/packages/brat/sqlbrat/utils/conflict_attributes.py", line 74, in calc_conflict_attributes
2023-07-27 17:34:51::     crossin = intersect_geometry_to_layer(intermediates_gpkg_path, 'road_crossings', ogr.wkbMultiPoint, reach_union, roads, epsg)
2023-07-27 17:34:51::   File "/usr/local/src/riverscapes-tools/packages/brat/sqlbrat/utils/conflict_attributes.py", line 125, in intersect_geometry_to_layer
2023-07-27 17:34:51::     geom = intersect_geometry_with_feature_class(geometry, feature_class, geometry_type, epsg)
2023-07-27 17:34:51::   File "/usr/local/src/riverscapes-tools/lib/commons/rscommons/vector_ops.py", line 648, in intersect_geometry_with_feature_class
2023-07-27 17:34:51::     geom_inter = geometry.intersection(geom_union)
2023-07-27 17:34:51:: AttributeError: 'NoneType' object has no attribute 'intersection'
2023-07-27 17:34:52:: <<BRAT PROCESS ENDED WITH AN ERROR>>\n\n
```
[FAILED-1704020102.log](https://github.com/Riverscapes/riverscapes-tools/files/12186457/FAILED-1704020102.log)

**Comment by jtgilbert** [comment]
I think that last one and this are both related to unanticipated consequences of running at HUC10 scale and having certain feature classes be empty. Will look into them.

**Comment by jtgilbert** [comment]
This problem in this HUC is that there's actually no flowlines. How should we deal with these cases...? @joewheaton @philipbaileynar

**Comment by philipbaileynar** [comment]
I feel brat should run to completion successfully.

Log entry stating zero feature count. 

This requires each brat process to be made tolerant of zero features. 

Having a valid but empty brat project will make all downstream processes (e.g RME) simpler if they don't have to have special handling for weird cases.
