### ISSUE TITLE
[BRAT Build] no such table: Agencies

### ISSUE THREAD

**Issue by KellyMWhitehead** [Riverscapes/riverscapes-tools#818]
After the last fix, brat is failing with the following message:
```
2023-07-28 18:15:52:: [error] [BRAT Build] no such table: Agencies
2023-07-28 18:15:52:: Traceback (most recent call last):
2023-07-28 18:15:52::   File "/usr/local/src/riverscapes-tools/packages/brat/sqlbrat/brat_build.py", line 334, in main
2023-07-28 18:15:52::     brat_build(
2023-07-28 18:15:52::   File "/usr/local/src/riverscapes-tools/packages/brat/sqlbrat/brat_build.py", line 205, in brat_build
2023-07-28 18:15:52::     conflict_attributes(outputs_gpkg_path, reach_geometry_path,
2023-07-28 18:15:52::   File "/usr/local/src/riverscapes-tools/packages/brat/sqlbrat/utils/conflict_attributes.py", line 55, in conflict_attributes
2023-07-28 18:15:52::     values = calc_conflict_attributes(flowlines_path, valley_bottom, roads, rail, canals, ownership, buffer_distance_metres, cell_size_meters, epsg, canal_codes, intermediates_gpkg_path)
2023-07-28 18:15:52::   File "/usr/local/src/riverscapes-tools/packages/brat/sqlbrat/utils/conflict_attributes.py", line 123, in calc_conflict_attributes
2023-07-28 18:15:52::     admin_agency(geopackage_path, reaches, ownership, results)
2023-07-28 18:15:52::   File "/usr/local/src/riverscapes-tools/packages/brat/sqlbrat/utils/conflict_attributes.py", line 170, in admin_agency
2023-07-28 18:15:52::     database.curs.execute('SELECT AgencyID, Name, Abbreviation FROM Agencies')
2023-07-28 18:15:52:: sqlite3.OperationalError: no such table: Agencies
2023-07-28 18:15:53:: <<BRAT PROCESS ENDED WITH AN ERROR>>\n\n
```

**Comment by jtgilbert** [comment]
this was after the fixes pushed this morning? @KellyMWhitehead

**Comment by KellyMWhitehead** [comment]
1701020201

[FAILED-1701020201.log](https://github.com/Riverscapes/riverscapes-tools/files/12216624/FAILED-1701020201.log)

**Comment by jtgilbert** [comment]
@KellyMWhitehead this should be fixed on dev now.
