### ISSUE TITLE
Channel Area Polygons can't be added to map in QRV VBET 3.1.0

### ISSUE THREAD

**Issue by shelbysawyer** [Riverscapes/riverscapes-tools#857]
I wanted to use [this VBET project](https://data.riverscapes.net/p/4bb72190-01a9-4c39-9be4-d0b6897b0d68/) to make a figure, but when I tried to add the channel area project to the map, I got an error message:

```
2023-11-24T04:00:08     WARNING    Traceback (most recent call last):
              File "C:/Users/shelby/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qrave_toolbar\src\dock_widget.py", line 319, in default_tree_action
              QRaveMapLayer.add_layer_to_map(item)
              File "C:/Users/shelby/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qrave_toolbar\src\classes\qrave_map_layer.py", line 197, in add_layer_to_map
              elif lyr[0] == ancestry[0][0]: # bit of a hacky way to test if map layer is in the same named qproject
             IndexError: list index out of range
```

I haven't encountered this with any other VBET projects I've been working with. when I opened the Channel Area project for this HUC, I was able to add the Channel Area Polygons to my map.

**Comment by jtgilbert** [comment]
I'm going to close b/c this has never come up again.
