### ISSUE TITLE
VBET mask size error

### ISSUE THREAD

**Issue by KellyMWhitehead** [Riverscapes/riverscapes-tools#925]
Two hucs. I can provide the rest of the logs if needed.

HUC: 1005001203 Level Path: 23002800010589
```
2024-02-19 00:20:52:: [error] [VBET] Mask and data not compatible: data size is 4511, mask size is 4512.
2024-02-19 00:20:52:: Traceback (most recent call last):
2024-02-19 00:20:52::   File "/usr/local/src/riverscapes-tools/packages/vbet/vbet/vbet.py", line 1201, in main
2024-02-19 00:20:52::   warnings.warn("urllib3 ({}) or chardet ({}) doesn't match a supported "
2024-02-19 00:20:52::     vbet(
2024-02-19 00:20:52::   File "/usr/local/src/riverscapes-tools/packages/vbet/vbet/vbet.py", line 653, in vbet
2024-02-19 00:20:52::     transformed[name] = np.ma.MaskedArray(
2024-02-19 00:20:52::   File "/usr/local/lib/python3.8/dist-packages/numpy/ma/core.py", line 2906, in __new__
2024-02-19 00:20:52::     raise MaskError(msg % (nd, nm))
2024-02-19 00:20:52:: numpy.ma.core.MaskError: Mask and data not compatible: data size is 4511, mask size is 4512.
2024-02-19 00:20:52:: <<RS CONTEXT PROCESS ENDED WITH AN ERROR>>
```
HUC: 1005001402 Level Path: 23002800001378
```
2024-02-19 00:21:19:: [error] [VBET] Mask and data not compatible: data size is 10698, mask size is 10699.
2024-02-19 00:21:19:: Traceback (most recent call last):
2024-02-19 00:21:19::   File "/usr/local/src/riverscapes-tools/packages/vbet/vbet/vbet.py", line 1201, in main
2024-02-19 00:21:19:: /usr/lib/python3/dist-packages/requests/__init__.py:89: RequestsDependencyWarning: urllib3 (1.26.18) or chardet (3.0.4) doesn't match a supported version!
2024-02-19 00:21:19::   warnings.warn("urllib3 ({}) or chardet ({}) doesn't match a supported "
2024-02-19 00:21:19::     vbet(
2024-02-19 00:21:19::   File "/usr/local/src/riverscapes-tools/packages/vbet/vbet/vbet.py", line 653, in vbet
2024-02-19 00:21:19::     transformed[name] = np.ma.MaskedArray(
2024-02-19 00:21:19::   File "/usr/local/lib/python3.8/dist-packages/numpy/ma/core.py", line 2906, in __new__
2024-02-19 00:21:19::     raise MaskError(msg % (nd, nm))
2024-02-19 00:21:19:: numpy.ma.core.MaskError: Mask and data not compatible: data size is 10698, mask size is 10699.
2024-02-19 00:21:19:: <<RS CONTEXT PROCESS ENDED WITH AN ERROR>>
```

**Comment by KellyMWhitehead** [comment]
HUC: 1705011407
Level Path: levelpath_None

```
2024-03-05 22:19:57:: [error] [VBET] Mask and data not compatible: data size is 0, mask size is 4188.
2024-03-05 22:19:57:: /usr/local/src/riverscapes-tools/packages/vbet/vbet/vbet.py:687: RuntimeWarning: invalid value encountered in sqrt
2024-03-05 22:19:57::   (np.sqrt(masked_prox) / np.sqrt(max_prox))
2024-03-05 22:19:57:: Traceback (most recent call last):
2024-03-05 22:19:57:: /usr/local/src/riverscapes-tools/packages/vbet/vbet/vbet.py:687: RuntimeWarning: invalid value encountered in sqrt
2024-03-05 22:19:57::   File "/usr/local/src/riverscapes-tools/packages/vbet/vbet/vbet.py", line 1220, in main
2024-03-05 22:19:57::   (np.sqrt(masked_prox) / np.sqrt(max_prox))
2024-03-05 22:19:57::     vbet(
2024-03-05 22:19:57:: /usr/local/src/riverscapes-tools/packages/vbet/vbet/vbet.py:687: RuntimeWarning: invalid value encountered in sqrt
2024-03-05 22:19:57::   File "/usr/local/src/riverscapes-tools/packages/vbet/vbet/vbet.py", line 672, in vbet
2024-03-05 22:19:57::   (np.sqrt(masked_prox) / np.sqrt(max_prox))
2024-03-05 22:19:57::     transformed[name] = np.ma.MaskedArray(
2024-03-05 22:19:57:: /usr/local/src/riverscapes-tools/packages/vbet/vbet/vbet.py:687: RuntimeWarning: invalid value encountered in sqrt
2024-03-05 22:19:57::   File "/usr/local/lib/python3.8/dist-packages/numpy/ma/core.py", line 2906, in __new__
2024-03-05 22:19:57::   (np.sqrt(masked_prox) / np.sqrt(max_prox))
2024-03-05 22:19:57::     raise MaskError(msg % (nd, nm))
2024-03-05 22:19:57:: /usr/local/src/riverscapes-tools/packages/vbet/vbet/vbet.py:687: RuntimeWarning: invalid value encountered in sqrt
2024-03-05 22:19:57:: numpy.ma.core.MaskError: Mask and data not compatible: data size is 0, mask size is 4188.
```

**Comment by jtgilbert** [comment]
@KellyMWhitehead I pushed a fix that successfully ran these problematic hucs, so hopefully it works everywhere
