### ISSUE TITLE
VBET Voronoi Error

### ISSUE THREAD

**Issue by KellyMWhitehead** [Riverscapes/riverscapes-tools#939]
HUC: 1604020202
```
2024-03-20 23:09:04:: [error] [VBET] Could not create Voronoi Diagram with the specified inputs.
2024-03-20 23:09:04:: Traceback (most recent call last):
2024-03-20 23:09:04::   File "/usr/local/lib/python3.8/dist-packages/shapely/ops.py", line 236, in voronoi_diagram
2024-03-20 23:09:04::     result = geom_factory(func(geom._geom, envelope, tolerance, int(edges)))
2024-03-20 23:09:04::   File "/usr/local/lib/python3.8/dist-packages/shapely/geometry/base.py", line 73, in geom_factory
2024-03-20 23:09:04::     raise ValueError("No Shapely geometry can be created from null value")
2024-03-20 23:09:04:: ValueError: No Shapely geometry can be created from null value
2024-03-20 23:09:04:: During handling of the above exception, another exception occurred:
2024-03-20 23:09:04:: Traceback (most recent call last):
2024-03-20 23:09:04::   File "/usr/local/src/riverscapes-tools/packages/vbet/vbet/vbet.py", line 1228, in main
2024-03-20 23:09:04::     vbet(
2024-03-20 23:09:04::   File "/usr/local/src/riverscapes-tools/packages/vbet/vbet/vbet.py", line 992, in vbet
2024-03-20 23:09:04::     split_vbet_polygons(output_vbet, segmentation_points,
2024-03-20 23:09:04::   File "/usr/local/src/riverscapes-tools/packages/vbet/vbet/vbet_segmentation.py", line 146, in split_vbet_polygons
2024-03-20 23:09:04::     voronoi = voronoi_diagram(
2024-03-20 23:09:04::   File "/usr/local/lib/python3.8/dist-packages/shapely/ops.py", line 241, in voronoi_diagram
2024-03-20 23:09:04::     raise ValueError(errstr)
2024-03-20 23:09:04:: ValueError: Could not create Voronoi Diagram with the specified inputs.
2024-03-20 23:09:04:: 100 - done.
2024-03-20 23:09:04:: <<RS CONTEXT PROCESS ENDED WITH AN ERROR>>
```

**Comment by jtgilbert** [comment]
I wasn't able to reproduce this. Wonder if there was a network blip while downloading inputs or something...

**Comment by KellyMWhitehead** [comment]
I'll give it a rerun and see if it happens again.

**Comment by KellyMWhitehead** [comment]
I also ran this successfully outside of cybercastor. Not sure why its only failing on cybercastor, but I am going to upload the local run and move on. 

Will investigate further if this happens again.
