### ISSUE TITLE
GDAL resampling method error from pygeoprocessing

### ISSUE THREAD

**Issue by jtgilbert** [Riverscapes/riverscapes-tools#970]
log from HUC: 1403000104

```
2024-06-24 15:32:49:: [error] [GDALError] ERR# 5 -- Unknown resampling method: 8.
2024-06-24 15:32:49:: Traceback (most recent call last):
2024-06-24 15:32:49::   File "/usr/local/bin/bratbuild", line 11, in <module>
2024-06-24 15:32:49::     load_entry_point('sqlbrat', 'console_scripts', 'bratbuild')()
2024-06-24 15:32:49::   File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 490, in load_entry_point
2024-06-24 15:32:49::     return get_distribution(dist).load_entry_point(group, name)
2024-06-24 15:32:49::   File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2854, in load_entry_point
2024-06-24 15:32:49::     return ep.load()
2024-06-24 15:32:49::   File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2445, in load
2024-06-24 15:32:49::     return self.resolve()
2024-06-24 15:32:49::   File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2451, in resolve
2024-06-24 15:32:49::     module = __import__(self.module_name, fromlist=['__name__'], level=0)
2024-06-24 15:32:49::   File "/usr/local/src/riverscapes-tools/packages/brat/sqlbrat/brat_build.py", line 30, in <module>
2024-06-24 15:32:49::     from sqlbrat.utils.conflict_attributes import conflict_attributes
2024-06-24 15:32:49::   File "/usr/local/src/riverscapes-tools/packages/brat/sqlbrat/utils/conflict_attributes.py", line 16, in <module>
2024-06-24 15:32:49::     from pygeoprocessing import geoprocessing
2024-06-24 15:32:49::   File "/usr/local/lib/python3.8/dist-packages/pygeoprocessing/__init__.py", line 11, in <module>
2024-06-24 15:32:49::     from . import geoprocessing
2024-06-24 15:32:49::   File "/usr/local/lib/python3.8/dist-packages/pygeoprocessing/geoprocessing.py", line 93, in <module>
2024-06-24 15:32:49::     gdal.WarpOptions(options=_GDAL_WARP_ALGORITHMS,
2024-06-24 15:32:49::   File "/usr/lib/python3/dist-packages/osgeo/gdal.py", line 660, in WarpOptions
2024-06-24 15:32:49::     return (GDALWarpAppOptions(new_options), callback, callback_data)
2024-06-24 15:32:49::   File "/usr/lib/python3/dist-packages/osgeo/gdal.py", line 4583, in __init__
2024-06-24 15:32:49::     this = _gdal.new_GDALWarpAppOptions(*args)
2024-06-24 15:32:49:: RuntimeError: Unknown resampling method: 8.
2024-06-24 15:32:50:: <<BRAT PROCESS ENDED WITH AN ERROR>>\n\n
```

**Comment by MattReimer** [comment]
Thanks @jtgilbert. We can close this if removing pygeoprocessing works. If it doesn't I will investigate upgrading GDAL on CC

**Comment by jtgilbert** [comment]
@MattReimer this is perplexing to me. This exact function has been moved to Anthro (with pygeoprocessing) and runs completely fine there on CC, but fails every time I try to run BRAT.

**Comment by jtgilbert** [comment]
Removed pygeoprocessing scripts

**Comment by jtgilbert** [comment]
@MattReimer 
Should I remove all refs to pygeoprocessing (e.g. requirements.txt) now?

**Comment by MattReimer** [comment]
Yeah. It's probably time to do that
